[WIP] [ANTAG] IT CAME FROM OUTER SPACE....
BeeStation/NSV13 pull request #1289
Opened 2021-03-13 18:51 UTC by Kmc2000

## About The Pull Request

![](https://cdn.discordapp.com/attachments/777650270603313152/819678632469463050/unknown.png)

WIP

* Run around maint competing with lizards for rats
* Try not to die

## Why It's Good For The Game

Not ready yet, just for testing!

## Changelog
:cl: Kmc2000 & Azlan
add: Added the bloodling
/:cl:

2021-03-14 22:33 UTC, Bokkiewokkie commented
What about AI shell functionality n stuff

2021-03-18 20:34 UTC, RuneQuester commented
Ah yes,Carrion

2021-03-21 08:31 UTC, Karmic-Skink commented
> Ah yes,Carrion

Not Carrion.

2021-03-23 07:28 UTC, Pontenerd commented
Mmmm, new badman

2021-04-04 12:59 UTC, Kmc2000 commented
Balance shit:
Gimp bloodling clings - remove most abilities, ESP. revive. Must be healed by the master
Give EMP screech to bloodling, remove from cling (MAYBE: give it a flash screech instead? Softer stun that way.)
Increase infest cling cost
Increase bloodling low tier hitbox
Bloodling absorb drops cloak, and CDs it.
Can only transfer maxBio - 10 biomass to avoid instadying

Consider:
Bloodling can give biomass to his clings to give them unlock points

Review:
Win condition. Waiting for 10 mins on a worm rampage kinda sucks ass

Fix:
WORM STUCK 
Bugged minion spawns (runtime in infest ... etc)

2021-04-07 12:23 UTC, Bokkiewokkie requested changes
You should probably make sure to check for any squads related issues and mention them as fixed if this PR fixes them. (#691 for example)

2021-04-07 12:23 UTC, Bokkiewokkie commented on code/game/machinery/doors/door.dm
> +	return (mover.pass_flags & PASSDOOR) || !density
Add //NSV13

2021-04-19 17:06 UTC, Kmc2000 commented on code/game/machinery/doors/door.dm
> +	return (mover.pass_flags & PASSDOOR) || !density
```suggestion
	return (mover.pass_flags & PASSDOOR) || !density //nsv13 - bloodling passdoor
```

2021-04-21 17:03 UTC, DrSirKnight commented
Becoming a headspider breaks a lot of things. You can still speak in changeling hivemind chat (With button and with prefix) if you're a headspider but you can't hear them and possibly nobody can hear you aswell. After getting revived you can't use points to purchase anything even if you have enough points left.

2021-04-21 17:10 UTC, Kmc2000 commented
-Headcrabs, investigate
-Nerf slam 
-Mindshield conversions are loud

2021-04-24 17:58 UTC, merged

2021-04-25 16:19 UTC, Bapldap commented
Last night when I was playing it I noticed that the ascended worm is basically on 'help' intent which causes some weird movements when you run over someone or a table. Also my health was constantly at a low state before I ascended, displaying 1% though I got it up 13% when I gathered biomass. Good antag, I found the stages before ascension more fun, it didn't seem like flesh path ascension fitted well with it.