New pill and chemical reaction, Dopamine
BeeStation/NSV13 pull request #1317
Opened 2021-03-28 01:22 UTC by IndusRobot

## About The Pull Request

Adds a pill to maintenance loot for all maps, and a recipe for chemists to make 

Rewards the consumer with a sense of instant gratification, proven to stimulate the rewards portion of the cerebrum with 110% effectiveness. 

## Why It's Good For The Game

The players keep complaining about quality of life this, powergamer that, crying over not getting what they want. This should fix all of these issues for the forseeable future 

Admins no longer have to police the playerbase with tickets, and no longer have to enforce the No Fun Allowed policy

## Changelog
:cl:
add: Added new things
add: Added more things
del: Removed old things
tweak: tweaked a few things
balance: rebalanced something
fix: fixed a few things
soundadd: added a new sound thingy
sounddel: removed an old sound thingy
imageadd: added some icons and images
imagedel: deleted some icons and images
spellcheck: fixed a few typos
code: changed some code
refactor: refactored some code
config: changed some config setting
admin: messed with admin stuff
server: something server ops should know
/:cl:

2021-03-28 08:44 UTC, Kmc2000 approved these changes
Outstanding move

2021-04-01 02:38 UTC, covertcorvid requested changes
Fix your changelog

2021-04-08 08:34 UTC, Kmc2000 commented on nsv13/code/game/objects/items/dopamine_pill.dm
> +/datum/chemical_reaction/dopamine
Can you make this uncraftable? This'd be a good gimmick for 10 hour eclipse rounds

2021-04-19 04:00 UTC, TheFakeElon commented on nsv13/code/game/objects/items/dopamine_pill.dm
> +	}
```suggestion
	if (!GLOB.crew_transfer_risa)
		priority_announce("[station_name()] has successfully returned to Outpost 45 for resupply and crew transfer, excellent work crew.", "Naval Command")
		GLOB.crew_transfer_risa = TRUE
		SSticker.mode.check_finished()
```

2021-04-19 17:10 UTC, Kmc2000 commented on nsv13/code/game/objects/items/dopamine_pill.dm
> +	}
:joker:

2021-06-02 02:29 UTC, closed without merging