Makes felinids more socially acceptable
BeeStation/NSV13 pull request #1395
Opened 2021-05-02 23:46 UTC by Pontenerd

## About The Pull Request
Removes uwuspeak when felinids are sick
## Why It's Good For The Game
If the ship gets nuked for uwuspeak, why should it be in code

## Changelog
:cl:
tweak: tweaked the messages felinids get when sick

2021-05-02 23:52 UTC, Karmic-Skink requested changes

2021-05-02 23:52 UTC, Karmic-Skink commented on code/modules/mob/living/carbon/human/species_types/felinid.dm
> +			var/sick_message = pick("You feel nauseous.", "You're not feeling so good.","You feel like your insides are melting.","You feel ill.")
//NSV13 tag

2021-05-03 00:00 UTC, Pontenerd commented on code/modules/mob/living/carbon/human/species_types/felinid.dm
> +			var/sick_message = pick("You feel nauseous.", "You're not feeling so good.","You feel like your insides are melting.","You feel ill.")
Done

2021-05-03 07:41 UTC, Kmc2000 approved these changes
I hate anime I hate anime I hate anime

2021-05-03 07:42 UTC, merged