Its a ship, not a station! Ship goal edition
BeeStation/NSV13 pull request #1453
Opened 2021-06-16 12:10 UTC by SharkeeByond

## About The Pull Request

Changes some of the text in station goal announcements so it suits NSV13

## Why It's Good For The Game

Muh immershuns

## Changelog
tweak: Tweaked station goals so they say ''ship'' instead of ''station'' now.
/:cl:

2021-06-16 12:29 UTC, Karmic-Skink requested changes
Core file changes require tagging.

2021-06-16 12:29 UTC, Karmic-Skink commented on code/modules/station_goals/bsa.dm
> +	 We need you to construct BSA-[rand(1,99)] Artillery position aboard your ship.
//NSV13 tag required

2021-06-16 12:29 UTC, Karmic-Skink commented on code/modules/station_goals/dna_vault.dm
> +	 We need you to construct a DNA Vault aboard your ship.
And here.

2021-06-16 12:29 UTC, Karmic-Skink commented on code/modules/station_goals/shield.dm
> +	return {"The ship is located in a zone full of space debris.
And here.

2021-06-16 18:29 UTC, SharkeeByond commented
Is it good now?

2021-06-20 15:48 UTC, covertcorvid approved these changes
A description of what changed is helpful if it's not on the same line as the change

2021-06-20 15:48 UTC, covertcorvid commented on code/modules/station_goals/bsa.dm
> +	 -Nanotrasen Naval Command"} //NSV13
```suggestion
	 -Nanotrasen Naval Command"} //NSV13 - changed station to ship
```

2021-06-20 15:48 UTC, covertcorvid commented on code/modules/station_goals/dna_vault.dm
> +	 Base vault parts are available for shipping via cargo."} //NSV13
```suggestion
	 Base vault parts are available for shipping via cargo."} //NSV13 - changed station to ship
```

2021-06-20 15:48 UTC, covertcorvid commented on code/modules/station_goals/shield.dm
> +			 "} //NSV13
```suggestion
			 "} //NSV13 - changed station to ship
```

2021-06-25 05:41 UTC, merged