[New map] NSV Hammerhead!
BeeStation/NSV13 pull request #1522
Opened 2021-07-06 20:19 UTC by Kmc2000

## About The Pull Request

The NSV Hammerhead is an entirely new, state of the art map designed around fun multiz interactions and verticality! It aims to join Atlas in the rotation for a classic lowpop map, but while also providing a great midpop option like Gladius. Similarly to Tycoon, it's also a fantastic highpop option, much like the Galactica, it can also support populations of up to 100!

The map has been rigorously tested over several months for quality assurance purposes, to ensure that it's released in its best state possible.

## Why It's Good For The Game

Deck 1: A spinally mounted corridor to allow for easy access to core systems
![image](https://user-images.githubusercontent.com/16804804/124660852-adfa6780-de9e-11eb-9473-9c02c2b17f9f.png)

Deck 2: The entire ship

![image](https://user-images.githubusercontent.com/16804804/124660843-aa66e080-de9e-11eb-95d6-0561f26f61cd.png)

The NSV Hammerhead is classed as a heavy cruiser. A large, unwieldy ship specialising in heavy weapons. It's equipped with a standard NAC / VLS / Gauss / PDC loadout in a unique, compact form factor! Due to its size, this ship uses flak to assist with point defense :)
![image](https://user-images.githubusercontent.com/16804804/124661714-c919a700-de9f-11eb-85cb-cffdca1b49b8.png)

Special thanks to Francinum for his amazing work in this collaboration :)) 

## Changelog
:cl: Francinum & Kmc2000
add: Added a brand new map, NSV Hammerhead! You'll see it around lowpop, medium pop, highpop, tidepop, infinite pop, at the heat death of the universe, and byond even that which we may comprehend with our mortal minds.
/:cl:

2021-07-06 20:21 UTC, triplezeta commented
good pr

2021-07-06 20:21 UTC, francinum commented
based

2021-07-06 20:22 UTC, RemervKeberb commented
Very wise PR

2021-07-06 20:25 UTC, Pontenerd commented
THE HAMMER STRIKES ANOTHER BLOW, SHE FLIES ONCE MORE

2021-07-06 20:42 UTC, athena413 commented
YOOOO

2021-07-06 21:37 UTC, retlaw34 commented
its been 3000 years

2021-07-06 21:52 UTC, AnCopper commented
Hammerhead? Haven't heard that name in a while, heh.

2021-07-07 03:38 UTC, Demoxide commented
Speedmerge this! Come on!

2021-07-07 12:08 UTC, Bokkiewokkie requested changes
Replace nwp with amW on line 39285 of Hammerhead1.dmm, it contains a memetic hazard.

2021-07-07 12:27 UTC, Kmc2000 commented on config/maps.txt
> +map hammerhead
no bokkie you can never escape the hammerhead

2021-07-18 19:37 UTC, Bokkiewokkie commented
> From the discord discussion:
> 
> The new spinal hallway does no good if it doesn't feature some fast way of transportation, it will just compound the fundamental hallway issue it's already experiencing. I do recommend throwing in a pair of conveyors or a pair of bluespace tiles for fast lane transportation on the top deck. It is our longest ship
> 
> If you do add conveyors or bluespace tiles, please lengthen it down to engineering! I spend all my time there

Obviously the correct solution to all our problems is adding the people tubes in maint that were part of the original Hammerhead design, I'm kind of disappointed to see you guys left those out in the final release.

2021-07-19 00:04 UTC, closed without merging