adds Hulljuice pack in cargo
BeeStation/NSV13 pull request #1543
Opened 2021-07-20 16:33 UTC by Florbman

adds Hulljuice tank + two extinguishers as a pack to order at cargo

## About The Pull Request

It simply adds a hulljuice tank and two extinguishers orderable in cargo at a price of 1200 credits

## Why It's Good For The Game

some maps don't have them and this would compensate for it

2021-07-20 22:38 UTC, Karmic-Skink requested changes
This PR needs to match the standard format of PRs.

eg There isn't actually a change log.

2021-07-21 06:20 UTC, Florbman commented
> 
> 
> This PR needs to match the standard format of PRs.
> 
> eg There isn't actually a change log.

oh i see, i added the changelog now

2021-07-28 03:35 UTC, Karmic-Skink commented
Unsure about the pricing of this, especially as we have that nagging budget card issue.
We'll test merge it as per standard and wait for feedback.

2021-07-28 17:07 UTC, Florbman commented
alright makes sense

2021-08-13 04:41 UTC, covertcorvid approved these changes

2021-08-14 01:54 UTC, merged