Laser Anti-missile System for solgov
BeeStation/NSV13 pull request #1553
Opened 2021-07-25 08:53 UTC by IndusRobot

## About The Pull Request

This contains no unique code yet completes half the required items 

- [x] New object ref 
- [x] Tactical and pilot cannot fire
- [ ] Autofires at enemy missiles 
- [ ] Add to solgov map

 Maintains lowpop requirements of no operation, minimal maintenance, to help keep rounds going 

## Why It's Good For The Game

## Changelog
:cl:
add: Laser AMS for solgov ships, a laser aesthetic for shooting down torps and keeping the ship alive 
/:cl:

2021-07-31 21:41 UTC, Kmc2000 commented on nsv13/code/modules/munitions/ship_weapons/_ship_weapon.dm
> +	if ( istype( src, /obj/machinery/ship_weapon/energy ) ) // Now 100% more modular!
We already have code to handle things like charge in phaser.dm, unless this is an "intangible" weapon?

I think a laser AMS should be a green laser. Reds, blues, and a green :)

2021-07-31 21:41 UTC, Kmc2000 commented on nsv13/code/modules/munitions/ship_weapons/ballistic_weapons/revision2/vls.dm
> +			if ( item )
This is kinda unecessary honestly, as this is a foreach, it shouldn't bring out a null, unless the item was QDELETED()

2021-07-31 21:41 UTC, Kmc2000 commented on nsv13/code/modules/munitions/ship_weapons/ballistic_weapons/revision2/vls.dm
> +				if ( W.autonomous )
Perhaps condense this into one if?

2021-07-31 21:41 UTC, Kmc2000 commented on nsv13/code/modules/munitions/ship_weapons/ballistic_weapons/revision2/vls.dm
> +			for ( var/datum/ship_weapon/W in automated_weapons )
Interesting approach, maybe a check for it not having any permitted AMS modes to save a bit of CPU?

2021-07-31 21:41 UTC, Kmc2000 commented on nsv13/code/modules/munitions/ship_weapons/energy_weapons/phaser.dm
> -/obj/machinery/ship_weapon/energy/fire(atom/target, shots = weapon_type.burst_size, manual = TRUE)
Oh this is what I was talking. Hmmm. Yeah, I don't like either of our solutions, but I guess yours is OK for now.

2021-08-15 22:18 UTC, Bokkiewokkie requested changes
Requested mapping changes:
- [ ] MaA should have a SSU for their bombsuit..
- [x] MaA should have a modular console in their office.
- [ ] MaA office walls should be made out of Duranium/reinforced.
- [x] MaA office needs a light switch. (yes this is absolutely critical)

2021-08-15 22:35 UTC, Bokkiewokkie approved these changes

2021-09-12 16:36 UTC, covertcorvid approved these changes

2021-09-15 00:02 UTC, covertcorvid approved these changes

2021-09-15 00:02 UTC, merged