Aetherwhisp sprite change
BeeStation/NSV13 pull request #1597
Opened 2021-08-23 18:32 UTC by IndusRobot

## About The Pull Request

Updates the sprite to match more closely to the map's geometry than the previous sprite even if it's not identical, courtesy of a fellow contributor Karmic Skink

![newaether](https://user-images.githubusercontent.com/22532898/130498984-0532b947-1ba1-433d-bcc7-e30f699b2c3f.png)

## Why It's Good For The Game

Tweaked Aetherwhisp sprite to look less brick shaped on the overmap 

## Changelog Karmic Skink
:cl:
tweak: Tweaked Aetherwhisp sprite to look less brick shaped on the overmap 
/:cl:

2021-08-23 18:40 UTC, Pontenerd commented
RIP combat pancake...

2021-08-23 19:05 UTC, Kmc2000 approved these changes
Not even bad TBH

2021-08-24 03:07 UTC, covertcorvid approved these changes

2021-08-24 03:16 UTC, covertcorvid requested changes
Still needs a thrust vector

2021-08-28 00:29 UTC, covertcorvid approved these changes

2021-09-03 04:35 UTC, merged