Makes experimental fighter armour useful.
BeeStation/NSV13 pull request #1663
Opened 2021-09-27 06:25 UTC by RemervKeberb

## About The Pull Request
Replaces the diamond cost with titanium
Lowers the weight to be slightly below regular armour

## Why It's Good For The Game

Currently there is not a single scenario where you would want to get experimental armour plating. This would make it useful in at least a single one. That being mining hasn't gotten any diamonds so you can't get your fancy engine and good armour. But science has thrown you a bone and researched experimental parts allowing you to at least slightly upgrade.

## Changelog
:cl:
balance: Experimental fighter armour is no longer useless.
/:cl:

2021-09-27 12:39 UTC, Karmic-Skink commented on nsv13/code/modules/research/designs/fighter_designs.dm
> +	materials = list(/datum/material/iron = 20000, /datum/material/plasma = 20000, /datum/material/titanium = 25000)
This is intentionally hard to get.

2021-09-27 12:40 UTC, Karmic-Skink requested changes
All of the experimental components are supposed to have drawbacks.

2021-09-27 12:43 UTC, Karmic-Skink requested changes

2021-09-27 12:43 UTC, Karmic-Skink commented on nsv13/code/modules/overmap/fighters/_fighters.dm
> +	weight = 0.90
This is intentional drawback.

2021-09-28 04:44 UTC, RemervKeberb commented
Gonna see about making a different one in that case.

2021-09-28 04:44 UTC, closed without merging