Steph's CIC reworks, part 1: Atlas
BeeStation/NSV13 pull request #1669
Opened 2021-09-29 22:16 UTC by James-source

## About The Pull Request

Changed the CIC of the atlas to something with more INFORMATION, as per the name.
It keeps the armoured feel, adds side viewing windows, an elevated command section, and secondary bridge staff stations for engineering data, security data, medical data, and cargo stuff.

In-Game Screenshot:
![Screenshot 2021-09-30 001307](https://user-images.githubusercontent.com/56017258/135356077-3f05756b-8ace-4639-85ee-44e31ba92adb.png)

## Why It's Good For The Game

Don't skimp on CICs, we need more intel.

## Changelog
:cl:
tweak: Tweaked the Atlas CIC to reorganize consoles
/:cl:

2021-09-29 23:14 UTC, Karmic-Skink commented
The firelock enclosures around every action seat is _incredibly_ hugbox.
-1

2021-09-30 00:27 UTC, James-source commented
The enclosures are in i think every map currently in rotation, the radlockers were there before, i just moved them somewhere else since there are no "airlocks" anymore.

2021-09-30 00:40 UTC, Karmic-Skink commented
> The enclosures are in i think every map currently in rotation, the radlockers were there before, i just moved them somewhere else since there are no "airlocks" anymore.

You mean the way they've all copied an Aetherwhisp feature? Yeah no. Hugbox.

2021-09-30 00:52 UTC, James-source commented
I'll remove 'em tomorrow then, not too attached to them anyways.

2021-09-30 04:27 UTC, James-source commented
Thingies removed, windows widened. I've left the rad lockers since they were there from the start and they are very very needed

2021-09-30 12:48 UTC, James-source commented
I think windows were the last thing people disliked, this should be ready to merge.

2021-09-30 18:24 UTC, Vasily2013 requested changes
- [x] The camera by the southern door is on the same tile as the spare safe. Move one.
- [ ] The camera by the AI upload doors is on the same tile as the turret controls. Move one.
- [ ] The scrubber south of the captain's seat should be more central in order to promote effectiveness of the scrubber. 
- [ ] If you're going to have redundant air (through the north door) you might as well have redundant power through there as well. 
- [ ] Having two disposals trunks is nice, but not necessary. All it really does is remove usable space. 
![image](https://user-images.githubusercontent.com/43328793/135510397-3acecb07-2efb-472b-91cf-2d83f9101b10.png)

2021-09-30 20:03 UTC, Absolutely-Steph commented
> * [ ]  Having two disposals trunks is nice, but not necessary. All it really does is remove usable space.
Would it be okay if i removed the disposals completely? i could use the space.

2021-09-30 20:17 UTC, Absolutely-Steph commented
I've just went ahead and did the thingies, anything else?

2021-10-01 00:44 UTC, Vasily2013 commented
> Would it be okay if i removed the disposals completely?

Honestly that's fine. CIC doesn't really need disposals. It's mainly in there for the "Clown funny yeet after b&e"

2021-10-01 00:45 UTC, Vasily2013 commented
As for other things I didn't see anything. Also in theory you can click the little boxes on my comment to cross them off... in theory.

2021-10-01 02:15 UTC, Absolutely-Steph commented
> As for other things I didn't see anything. Also in theory you can click the little boxes on my comment to cross them off... in theory.

yeah i tried that and it didnt work, ah well.

2021-10-01 22:40 UTC, Vasily2013 approved these changes
Looks nice to me.

2021-10-01 23:56 UTC, Vasily2013 approved these changes
![IntriguedTarsier](https://user-images.githubusercontent.com/43328793/135696820-24decb7a-edd2-4dcb-82a1-82798ce0b873.jpg)

2021-10-02 03:20 UTC, bluey89962 commented
The APC appears to not be connected to the power grid. 
![image](https://user-images.githubusercontent.com/42455169/135702012-b37523f5-f63c-491c-a39f-c5bf1a4998af.png)

2021-10-02 08:17 UTC, Absolutely-Steph commented
> The APC appears to not be connected to the power grid. ![image](https://user-images.githubusercontent.com/42455169/135702012-b37523f5-f63c-491c-a39f-c5bf1a4998af.png)

ahgh that must have happened when bokkie told me to move it, woe is me

2021-10-02 22:18 UTC, Bokkiewokkie requested changes
Here are the things I noticed:
![image](https://user-images.githubusercontent.com/43698041/135733155-259fbd29-77c7-4e12-a599-b6158c6ef552.png)

2021-10-02 22:27 UTC, Absolutely-Steph commented
> Here are the things I noticed: ![image](https://user-images.githubusercontent.com/43698041/135733155-259fbd29-77c7-4e12-a599-b6158c6ef552.png)

you know you didn't have to do that if you didnt feel well right? PRs can wait, even if the owner is giddy

2021-10-02 22:41 UTC, Absolutely-Steph commented
did most of the things except change floor color and move spare safe, because the safe is only ever gonna get used once, and having it close to important stations doesnt matter (also no space reeee)

2021-10-03 21:35 UTC, Bokkiewokkie approved these changes

2021-10-04 01:43 UTC, Vasily2013 approved these changes
![image](https://user-images.githubusercontent.com/43328793/135781950-69a0192d-ea85-438d-9904-b03de13c4e23.png)

2021-10-04 01:51 UTC, merged