Makes the FTL auto-spool and the UI show that it's charged when it is
BeeStation/NSV13 pull request #1722
Opened 2021-11-05 15:29 UTC by Bokkiewokkie

## About The Pull Request

Makes the FTL auto-spool by default, awaiting a new and improved way of spooling the FTL but this will be a temporary way to make spooling less of a hassle.

## Why It's Good For The Game

https://discord.com/channels/602204464417472601/602206782596710468/829036340381351937
Only 5 moths too late :)
![image](https://user-images.githubusercontent.com/43698041/140536189-ad68abcc-b040-4d29-ba68-2fc9516ae942.png)

## Changelog
:cl:
tweak: Made the FTL drive auto-spool
/:cl:

2021-11-05 18:02 UTC, Bokkiewokkie commented on nsv13.dme
> +#include "nsv13\code\modules\mapping\custom_map_template.dm"
I guess this fucking broke the compiler of the box, absolutely genius

2021-11-06 05:57 UTC, Karmic-Skink requested changes
Moth memes aren't a valid reason as to why this is good for the game.

2021-11-07 18:13 UTC, Bokkiewokkie commented
Okay I played a round with this it's pretty lame

2021-11-08 04:38 UTC, covertcorvid approved these changes

2021-11-12 18:35 UTC, merged