Makes ammo stackers upgradable via matter bins
BeeStation/NSV13 pull request #1768
Opened 2021-12-28 15:51 UTC by Omppusolttu

## About The Pull Request

Ammo stacker max capacity can now be upgraded via matter bins:
T1 = 12
T2 = 24
T3 = 36
T4 = 48

## Why It's Good For The Game

Ammo stackers are not used for their intended purpose of holding high explosive materials atleast in the case of gunpowder due to their incredibly low capacity, especially when compared to the abundant crates. This PR intends to remedy that.

## Changelog
:cl:
add: Matter bins to Ammo stackers
/:cl:

2021-12-28 22:07 UTC, Karmic-Skink requested changes
Those numbers are way too high.

2021-12-29 22:40 UTC, Bokkiewokkie commented
@Omppusolttu I think it'd be better if you changed the amount increase per tier instead of the default capacity instead of doing what you did now.

2021-12-29 22:57 UTC, Karmic-Skink requested changes
Unbalanced as heck.

2021-12-29 22:57 UTC, Karmic-Skink commented on nsv13/code/modules/munitions/ship_weapons/ballistic_weapons/revision2/automation.dm
> +	req_components = list(/obj/item/stock_parts/matter_bin = 1)
Given the amount this is holding, it should be more matter bins.

2021-12-29 22:57 UTC, Karmic-Skink commented on nsv13/code/modules/munitions/ship_weapons/ballistic_weapons/revision2/automation.dm
> +	var/max_capacity = 10	//Max cap for holding.
Reducing this number is going to cause havoc where it is already mapped in.

2021-12-29 22:57 UTC, Karmic-Skink commented on nsv13/code/modules/munitions/ship_weapons/ballistic_weapons/revision2/automation.dm
> +		max_capacity = MB.rating*10
Increasing by 100% of the base value per tier is way too over the top.

2021-12-30 12:05 UTC, Karmic-Skink requested changes

2021-12-30 12:05 UTC, Karmic-Skink commented on nsv13/code/modules/munitions/ship_weapons/ballistic_weapons/revision2/automation.dm
> +/obj/machinery/ammo_sorter/RefreshParts()
This block isn't taking into account that you've changed it to use three bins.

2022-01-04 22:03 UTC, Bokkiewokkie commented on nsv13/code/modules/munitions/ship_weapons/ballistic_weapons/revision2/automation.dm
> +		max_capacity += MB.rating*1+3
```suggestion
		max_capacity += MB.rating+3
```
x*1 = x

2022-01-14 21:38 UTC, Bokkiewokkie approved these changes

2022-01-14 21:39 UTC, merged