Removes Rocinante from Tycoon, adds mining sabre launchsite, plus minor bugfixes
BeeStation/NSV13 pull request #1825
Opened 2022-02-14 01:40 UTC by IndusRobot

## About The Pull Request

Updates Tycoom with mining sabres and mining equipment setup room 

The old mining shuttle has been replaced with an elevator to the new launchsite 

![engi4](https://user-images.githubusercontent.com/22532898/153785872-093cc29d-5ebd-4fda-84a5-ee20a4bb2597.png)

## Why It's Good For The Game

Asteroid mining

Fixes #1796 
Fixes #1581 
Addresses 732 but doesn't mark it as fixed because it's a megaissue. https://github.com/BeeStation/NSV13/issues/732
Fixes #717 (this isn't actually an issue but w/e)

## Changelog
:cl:
del: Removed Rocinante from Tycoon
add: Added mining sabres to Tycoon
fix: Fixed disconnected pipes, duplicate APCs, missing air alarms in various areas 
fix: Fixed brig physician not having bare minimum access to access their medical station
fix: Fixed tycoon munitions factory not working most of the time 
fix: Fixed tycoon bots having no patrol routes 
/:cl:

2022-02-14 02:39 UTC, Vasily2013 requested changes
I might be insane, but I didn't see any hardsuits.

2022-02-15 00:41 UTC, Vasily2013 submitted a review, later dismissed
Mining functions.

Missile factory failed to produce a missile 66% of the times that I tried to make one. I think the issue is the missiles are dispensed at the first station, and the conveyor can move things out of the way too quickly.

Everything else looks good.

2022-02-18 20:28 UTC, Bokkiewokkie commented
Going to TM and review later because I'm short on time

2022-03-11 16:25 UTC, Bokkiewokkie approved these changes

2022-03-11 16:25 UTC, merged