Felinids don't like getting wet, and pulling them by the tail makes them upset
BeeStation/NSV13 pull request #1830
Opened 2022-02-18 04:47 UTC by red031000

## About The Pull Request

merges (with some modifications)
tgstation/tgstation#50635
tgstation/tgstation#62777
tgstation/tgstation#59506

adds negative moodlets for pulling by the tail, for felinids being sprayed/splashed with water, and for felinids taking a shower

## Why It's Good For The Game

some fun for felinids by making them act closer to cats

## Changelog
:cl:
add: felinids don't like getting wet
add: pulling someone by the tail makes them upset
/:cl:

2022-02-18 05:29 UTC, Karmic-Skink commented
Generally speaking, we inherit this sort of stuff from Beestation.

2022-02-18 05:42 UTC, Absolutely-Steph commented
> Generally speaking, we inherit this sort of stuff from Beestation.

Bee is cringe and would never allow this.

2022-02-18 05:59 UTC, Bobbanz1 commented
> > Generally speaking, we inherit this sort of stuff from Beestation.
> 
> Bee is cringe and would never allow this.

Can confirm, Bee nuked lavalands loot table while we just overwrote it with our own mining system

2022-02-18 15:24 UTC, bluey89962 commented
Lord have mercy on this PR.

2022-02-18 19:45 UTC, Karmic-Skink commented
> > > Generally speaking, we inherit this sort of stuff from Beestation.
> > 
> > 
> > Bee is cringe and would never allow this.
> 
> Can confirm, Bee nuked lavalands loot table while we just overwrote it with our own mining system

That is not why we have our own mining system.

Believe it or not, asteroid mining via sabres has been on the cards for a *very* long time.

2022-02-25 20:04 UTC, Bokkiewokkie commented
> Generally speaking, we inherit this sort of stuff from Beestation.

This, if this is PR'd to beestation and merged we will merge it here aswell, if it is rejected we'll take a look at if we want it on NSV as an exception from bee. Same deal as #1840.

2022-03-16 23:38 UTC, TheFakeElon commented
> > Generally speaking, we inherit this sort of stuff from Beestation.
> 
> Bee is cringe and would never allow this.

Read bee #general for <2 minutes and you'll start to question that belief

2022-03-17 04:54 UTC, Absolutely-Steph commented
> > > Generally speaking, we inherit this sort of stuff from Beestation.
> > 
> > 
> > Bee is cringe and would never allow this.
> 
> Read bee #general for <2 minutes and you'll start to question that belief

yeah they just had their annual felinid removal PR and crossed gave permission to roll felinids into humans as an aesthetic change. This PR has no prospects to get merged on bee, they are already clutching their pearls at the felinids mere existance.

2022-03-25 19:06 UTC, Bokkiewokkie requested changes

2022-04-02 00:21 UTC, red031000 commented
note to self: make fire extinguishers work on felinids too

2022-04-22 19:57 UTC, Bokkiewokkie approved these changes
Still some redundant comments in the nsv mood_event file. Other than that it's good now

2022-04-22 19:59 UTC, Bokkiewokkie commented
> note to self: make fire extinguishers work on felinids too

Did you want to make this a seperate PR or still incorporate it here? We can hold off on merging if it is the latter.

2022-04-23 19:07 UTC, red031000 commented
fire extinguishers do work, it turns out, it's just not much of a noticable effect to everyone around the felinid in question, which makes me wonder whether I need to change it to something else, or add a message

2022-05-06 18:52 UTC, merged