add minimum population requirement for kill objectives to changeling and wizzard
BeeStation/NSV13 pull request #1921
Opened 2022-05-20 07:55 UTC by Kenionatus

## About The Pull Request

Only give kill objectives to wizards and changelings if the population is above MIN_POP_KILL_OBJECTIVES from config\game_options.txt
 

## Why It's Good For The Game

Brings wizards and changelings in line with traitors. Consistency is good because people get upset about inconsistencies. Also, lowpop murder is lame.

## Changelog
:cl:
tweak: No longer give kill objectives to wizards and changelings on low pop.
/:cl:

2022-05-20 07:56 UTC, Kenionatus commented
Wasn't able to really test it because I don't know of any way to create dummy players. It does however not crash if I local host, join as only player and make myself wizard or changeling. Also didn't give me any kill objectives, tho there isn't anyone to kill so that might not have any connection to my code.

2022-05-22 17:57 UTC, Kenionatus commented
Fixes #1884

2022-05-23 08:59 UTC, Bokkiewokkie requested changes
Mark your changes with //nsv13 if they're not in the nsv folder

2022-05-28 22:58 UTC, Kenionatus commented on code/modules/antagonists/changeling/changeling.dm
> +					escape_objective_possible = FALSE
I feel like that might be slightly misleading in the changeling case. Everything except the commented lines is just a shift in indentation that stems from those and the diff shows a much bigger change than logically happened imo. If you think it's still worth strictly sticking to an end comment I'll not object tho.

Wizzard file is a clear case for an "//nsv13 end". Added in [this commit](https://github.com/BeeStation/NSV13/commit/bf14d0e271af637d249a2b058141adf1c46844b2).

2022-06-10 21:16 UTC, Bokkiewokkie approved these changes

2022-06-14 16:40 UTC, merged