make gauss guns require no power
BeeStation/NSV13 pull request #1951
Opened 2022-06-14 18:56 UTC by Kenionatus

## About The Pull Request

Gauss guns currently require power in the turret's room to operate. Prebuilt turrets seem to be powered by default but rebuilt turrets are usually unpowered because they're in an area without APC. Making them require no power is an easier fix than making new powered areas in space for each gauss battery.

## Why It's Good For The Game

bugfix without much side effects (Fixes #1855)

## Changelog
:cl:
fix: rebuilt gauss guns should now always be usable
/:cl:

2022-06-14 21:00 UTC, Karmic-Skink commented
Fix it properly.

2022-06-15 08:15 UTC, Kenionatus commented
@Karmic-Skink 
> Fix it properly. -1

I'm not much of a mapper. If you go through all of the maps and add APC powered areas, I'll see if I can change mapper placed Gauss Guns to no have power by default so unpowered ones get caught early.

2022-06-15 21:29 UTC, Karmic-Skink commented
> @Karmic-Skink
> 
> > Fix it properly. -1
> 
> I'm not much of a mapper. If you go through all of the maps and add APC powered areas, I'll see if I can change mapper placed Gauss Guns to no have power by default so unpowered ones get caught early.
> 
> Addendum: NAC turrets were previously changed to not require power, so this PR would bring them in line with each other.

NACs are chemically propelled.

Draw power from the chair location.

2022-06-17 16:56 UTC, Bokkiewokkie requested changes
Changing the maps to have the gauss bay areas cover the turrets on the other deck would be a better solution.

2022-06-18 11:09 UTC, Karmic-Skink commented
> Changing the maps to have the gauss bay areas cover the turrets on the other deck would be a better solution.

That sounds like a dodgy work around.

2022-06-20 20:33 UTC, Kenionatus commented
I think the best solution would be to wire a cable to every gauss gun and make them draw a significant (but not too large not not majorly mess up energy balancing) amount from it.

2022-07-29 19:47 UTC, Bokkiewokkie commented
> I think the best solution would be to wire a cable to every gauss gun and make them draw a significant (but not too large not not majorly mess up energy balancing) amount from it. I just don't really feel like mapping.
> 
> Taking power from below would be quite the overhaul, since the "actual" gauss gun is the turret, which is classified as a machine. Loading rack is an optional part automatically created below if possible and gunner chair needs to be constructed manually and is also optional.

Can you please (at least just by coding, the mapping can be done by someone else if you really don't want to) add that instead then? We're not gonna merge this PR in its current state

2022-07-29 23:44 UTC, Kenionatus commented
Ok. Put this on the top of my mental NSV todo list.

2022-10-29 14:39 UTC, closed without merging