[DNM] Bot Multi-Z Movement
BeeStation/NSV13 pull request #1983
Opened 2022-07-07 07:14 UTC by Bobbanz1

## About The Pull Request
Right, first of all!
Ports some of the code introduced by this PR: [tgstation/tgstation/pull/65906](https://github.com/tgstation/tgstation/pull/65906)
Full credit for the code used to find the closest ladder goes to cacogen.

Second of all!
Some bots, possibly all of them, are now capable of moving between Z-levels if one of the following conditions are met:

- The AI has slammed down a waypoint on another Z-level, like on the bottom deck or the upper deck.
- - If this happens then the bot will instantly head for the nearest ladder it can find from its current position, upon arriving to this ladder it will check the original waypoint and use the ladder to either go up or down, afterwards it resets the bot call command before promptly running it yet again, this time with the original waypoint as the final destination.
- A Navigation Beacon has a destination that's located on another Z-level, currently it's restricted to only check Z-level 2 and 3 which seems to always be the Z-levels the ships various decks are located on. 
- - Upon detecting the beacons location on another deck, the bot will try heading for the nearest ladder possible, however due to the fact that they don't normally have all access, I've introduced an access specifically for bots, which is called ACCESS_BOT_OVERRIDE who's number is 501, currently only five doors on the Atlas has that access attached to them. 
- - - Upon reaching the ladder it will go down, or up it, and promptly forget the original destination and start heading for the nearest beacon it can find (could possibly also be trying to reach the next beacon from the original destination one)

The system doesn't yet support the ability to summon bots from other z-levels using one's PDA. 

Currently only the Atlas has a somewhat semi-working patrol network, although it sometimes gets stuck upstairs if the bot originally started its route on the navigation beacon outside the Head of Security's office. 

So far I've not implemented this system for Mulebots. 

## Why It's Good For The Game
Bot uses ladders. Bot is now advanced boi.

## Changelog
:cl: 
add: Added the ability for bots to go up and down ladders.
add: Added the ability for bots to find a route to another Z-level if called to it.
add: Added the ability for bots to have a patrol route going downstairs or upstairs using ladders
code: Potentially broke the bots ability to patrol if going by how that bot kept getting stuck on that one navigation beacon
/:cl:

2022-08-10 11:04 UTC, Bokkiewokkie approved these changes
Mapping approved

2022-08-10 11:20 UTC, Bobbanz1 commented on code/__DEFINES/access.dm
> +
Seems to be leftover from when I had the idea of trying to implement an access specifically for bots.

2022-08-11 05:44 UTC, Bobbanz1 commented on code/__DEFINES/access.dm
> +
It has been resolved

2022-10-29 14:44 UTC, Bokkiewokkie requested changes

2022-10-29 14:44 UTC, Bokkiewokkie commented on code/modules/mob/living/simple_animal/bot/medbot.dm
> +	access_card.access += ACCESS_MAINT_TUNNELS //NSV13 - DIFFERENCE BETWEEN CODEBASE
```suggestion
	access_card.access += ACCESS_MAINT_TUNNELS //NSV13 - Added maintenance access for bots
```
Please describe the type of change made in the comments.

2022-10-29 14:58 UTC, Bokkiewokkie approved these changes

2022-10-29 15:00 UTC, merged