Puts the Fist of Sol back in the bag.
BeeStation/NSV13 pull request #2017
Opened 2022-08-14 21:20 UTC by QAI-07

## About The Pull Request

For a while now, on rare occasions, the Fist of Sol would appear in the Rubicon sector along with an identical clone of itself. While it still works as intended, it's appearance outside of strict admin intervention was _not_ intended. I've just finally gotten up to fix it.

## Why It's Good For The Game

Fix man good.
Also, I can now buff it without worry of it appearing randomly and jumpscaring the crew with funky new weapons.

## Changelog
:cl:
fix: fixed the Fist of Sol Boss showing up when it shouldn't. 
/:cl:

2022-08-16 07:54 UTC, Bokkiewokkie reviewed
just a small thing...

2022-08-16 07:54 UTC, Bokkiewokkie commented on nsv13/code/modules/overmap/ai-skynet.dm
> +	taunts = list("What a pleasure that we should meet again. I hope you won't disapoint!")
```suggestion
	taunts = list("What a pleasure that we should meet again. I hope you won't disappoint!")
```

2022-08-16 18:39 UTC, DeltaFire15 submitted a review, later dismissed
Instead of changing its type away from ../syndicate/ai which leads to issues with things that check for this subtype, add it to the enemy_blacklist in ../subsystem/starsystem.dm.

2022-08-21 00:38 UTC, red031000 commented
![image](https://user-images.githubusercontent.com/13968885/185770640-06638503-99a8-40b4-a2c0-5e2b5e05d7e6.png)
doesn't work

2022-08-21 00:40 UTC, red031000 commented
ok, correction, does work, however the same issue happens to sol's revenge, might be an idea to fix it as well?

2022-08-21 00:45 UTC, Pontenerd commented
![image](https://user-images.githubusercontent.com/68692362/185770772-b9257641-bd37-4eb3-8a91-a52ea5c9dddf.png)
round id is 4800

2022-08-24 15:28 UTC, Bokkiewokkie commented
> ![image](https://user-images.githubusercontent.com/68692362/185770772-b9257641-bd37-4eb3-8a91-a52ea5c9dddf.png) round id is 4800

![SyndicateFlagshipInfograph](https://user-images.githubusercontent.com/43698041/186459245-364bf13c-c9fb-4feb-8c70-ebf2d4fff923.png)

2022-09-15 10:58 UTC, Bokkiewokkie commented
@QAI-07 Are you going to adress DeltaFire's requested changes?

2022-09-17 18:46 UTC, QAI-07 commented
@Bokkiewokkie I would if I had even the slightest idea of how to do any of that.

2022-10-01 18:52 UTC, Bokkiewokkie requested changes

2022-10-03 08:25 UTC, Bokkiewokkie approved these changes

2022-10-03 08:26 UTC, merged