Glock stop
BeeStation/NSV13 pull request #2024
Opened 2022-08-19 14:31 UTC by TheScienceOfKSP

## About The Pull Request
Adds new sprites/sprite edits for the glocks.
Adds a burst-fire mode for the Security version of the Glock.

## Why It's Good For The Game
Different flavours of Glocks help differentiate ranks even further
The burst-fire mode for the SecGlock should help even the odds for MPs against KNPCs and their ungodly firerate.
New colors for the glocks look pretty as well (Except crewmen, i stole their stripes)

## Changelog
:cl:
add: Added new thingies
add: Added more things
del: Removed old things
tweak: tweaked a few things
balance: Added a 3-round burstfire mode to the Sec-Glock
fix: fixed a few things
soundadd: added a new sound thingy
sounddel: removed an old sound thingy
imageadd: Added a grand total of 9 new icons for Glocks
imagedel: deleted some icons and images
spellcheck: fixed a few typos
code: changed some code
refactor: refactored some code
config: changed some config setting
admin: messed with admin stuff
server: something server ops should know
/:cl:

![Guns](https://user-images.githubusercontent.com/8210740/185641566-694e523d-ff67-4b19-83ab-27b08ee935c1.png)

2022-08-19 22:43 UTC, Karmic-Skink requested changes
Remove all the unused terms and the picture from your changelog.

2022-08-22 12:27 UTC, TheScienceOfKSP commented
> Remove all the unused terms and the picture from your changelog.

Done, as for the picture, whats the issue with it?

2022-08-26 10:32 UTC, Karmic-Skink commented
As apparently the instruction was too hard, I've moved the picture.

2022-09-05 18:47 UTC, covertcorvid approved these changes

2022-09-17 03:39 UTC, merged