Adds Ration Packs to Sustenance Vendors
BeeStation/NSV13 pull request #2034
Opened 2022-08-26 01:58 UTC by Kenionatus

## About The Pull Request
Adds 12 ration packs to the list of available items in the sustenance vendor and at the same time reduces the number of available soggy tofu bars by the same amount. Whether that's necessary and whether soggy tofu even needs to remain in the vendor is up for discussion.

Adds fitting text to product_slogans (the ads that the machine occasionally speaks). Also moves some text from product_adds to product_slogans so that the machine speaks those. I don't think product_adds works any more anyway.

In the future, the sustenance vendor's description should probably be changed to reflect that it's not just for prisoners, considering it's in a public space on the Aetherwhisp. Maybe a subtype for public places would be good. Or we just change the description to something more neutral, not mentioning prisoners.

## Why It's Good For The Game
Ration packs are the thing that militaries feed to their soldiers if there isn't the capacity to make actual food. We're kind of a military server, so it makes sense to have them. The atlas even has them on the mess hall tables. The Aetherwhisp has a sustenance vendor in its dining area and this seems like the perfect place to me to distribute those rations.

## Changelog
:cl:
add: Added ration packs to sustenance vendors
/:cl:

2022-08-26 07:53 UTC, Bokkiewokkie requested changes

2022-08-26 07:53 UTC, Bokkiewokkie commented on code/modules/vending/sustenance.dm
> +	product_ads = "Sufficiently healthy.;Efficiently produced tofu!;Mmm! So good!;Have a meal.;You need food to live!;Have some more candy corn!;Try our new ice cups!;Rememver: Ration packs save lifes,
```suggestion
	product_slogans = "Enjoy your meal.;Enough calories to support strenuous labor.;Sufficiently healthy.;Efficiently produced tofu!;Mmm! So good!;Have a meal.;You need food to live!;Have some more candy corn!;Try our new ice cups!;Rememver: Ration packs save lifes, soldier!;Don't believe the lies about ration packs.; Ration packs: custom tailored to the Spaceman's taste!" //NSV13 added lines referencing ration packs
	product_ads = "Sufficiently healthy.;Efficiently produced tofu!;Mmm! So good!;Have a meal.;You need food to live!;Have some more candy corn!;Try our new ice cups!;Remember: Ration packs save lifes, soldier!;Don't believe the lies about ration packs.; Ration packs: custom tailored to the Spaceman's taste!" //NSV13 added lines referencing ration packs
```
Add comments to indicate we changed it from the base code.

2022-08-26 07:53 UTC, Bokkiewokkie commented on code/modules/vending/sustenance.dm
> +					/obj/item/reagent_containers/food/snacks/rationpack = 12,
```suggestion
	products = list(/obj/item/reagent_containers/food/snacks/tofu/prison = 12, //NSV13 halved available tofu
					/obj/item/reagent_containers/food/snacks/rationpack = 12, //NSV13 added ration packs
```
Ditto

2022-08-26 20:39 UTC, Kenionatus commented
Test fail looks very much unrelated to this PR.

2022-08-26 22:54 UTC, covertcorvid approved these changes
This makes the lizard sad, but it's a reasonable change

2022-09-01 08:00 UTC, Bokkiewokkie approved these changes

2022-09-04 00:33 UTC, merged