Emotional Support Torpedo
BeeStation/NSV13 pull request #2039
Opened 2022-08-29 00:04 UTC by DeltaFire15

## About The Pull Request
Title. Use if enemy requires a hug or several.

## Why It's Good For The Game
![rgbliz](https://user-images.githubusercontent.com/46569814/187100387-3bb5792a-672a-44b3-b41c-5e816f4ae5cc.gif)

## Changelog
:cl:
add: emotional support torp.
del: my sanity which is too low to sprite a funny sprite.
/:cl:

2022-08-29 00:13 UTC, QAI-07 commented
are you okay?

2022-08-29 00:59 UTC, Pontenerd commented
> are you okay?

is anyone?

2022-08-29 08:49 UTC, Bokkiewokkie requested changes
You should be able to hug it by interacting 🫂

2022-08-30 15:28 UTC, Bokkiewokkie requested changes

2022-08-30 15:28 UTC, Bokkiewokkie commented on code/datums/mood_events/generic_positive_events.dm
> +
```suggestion
```
Ditto,
Since all of this is unique to NSV we can just define it in /nsv13/code/datums/mood_events/nsv_events.dm instead

2022-08-30 15:28 UTC, Bokkiewokkie commented on code/datums/components/crafting/recipes.dm
> +
```suggestion
```
Should be moved to /nsv13/code/datums/components/crafting/recipes.dm instead

2022-08-30 15:29 UTC, Bokkiewokkie commented on code/datums/mood_events/generic_positive_events.dm
> +
Why did it place this comment second... :tragedy:

2022-09-17 08:15 UTC, covertcorvid approved these changes

2022-09-23 09:06 UTC, Bokkiewokkie approved these changes
![52373287457_73a2b75649_o](https://user-images.githubusercontent.com/43698041/191927824-ed889bba-c0c8-43ab-b716-7ce3a0351b65.jpg)

2022-09-23 09:07 UTC, merged