RCD constructed airlocks will now use NSV icons
BeeStation/NSV13 pull request #2123
Opened 2022-10-28 04:11 UTC by someone543

## About The Pull Request
Airlocks made using an RCD will now be NSV airlocks. If players for whatever reason want the old airlock icons, the airlock painter is available.

## Why It's Good For The Game
NSV airlocks look nice, while old airlocks don't really fit in.

## Changelog
:cl:
tweak: RCD airlocks will now use NSV icons
/:cl:

2022-10-28 13:28 UTC, Bokkiewokkie requested changes

2022-10-28 13:28 UTC, Bokkiewokkie commented on code/game/objects/items/RCD.dm
> +	var/color = initial(proto.color) //NSV13 allows airlocks with color vars (mining airlocks) to be colored
var/color is already an /atom variable, please change it to something else like var/co like what was done for var/ic

2022-11-08 23:48 UTC, covertcorvid approved these changes

2022-11-15 13:53 UTC, Bokkiewokkie approved these changes

2022-11-15 13:54 UTC, merged