Adds Highjack, a new drug for IPC's!
BeeStation/NSV13 pull request #2129
Opened 2022-10-31 17:44 UTC by Pontenerd

## About The Pull Request

Adds a new drug, similar to space drugs, but only for ipcs, when overdosed, they detach their heads.

## Why It's Good For The Game

This now means all our crewmembers can be arrested for being high at their station

## Changelog
:cl:
add: Added Highjack, a drug similar to space drugs, but for IPC's
/:cl:

2022-10-31 18:50 UTC, Bokkiewokkie requested changes

2022-10-31 18:50 UTC, Bokkiewokkie commented on code/modules/reagents/chemistry/reagents/drug_reagents.dm
> +
Put this in the NSV folders

2022-10-31 18:50 UTC, Bokkiewokkie commented on code/modules/reagents/chemistry/recipes/drugs.dm
> +
Ditto

2022-11-02 20:35 UTC, Bokkiewokkie requested changes

2022-11-02 20:35 UTC, Bokkiewokkie commented on code/modules/reagents/chemistry/reagents/drug_reagents.dm
> +
Please move these into a NSV file as well (and remove that added first line in the file.

2022-11-02 20:35 UTC, Bokkiewokkie commented on code/modules/reagents/chemistry/recipes/drugs.dm
> +
extra line :taco:

2022-11-10 23:27 UTC, Bokkiewokkie commented on code/modules/reagents/chemistry/reagents/drug_reagents.dm
> +
```suggestion
```

2022-11-19 02:03 UTC, covertcorvid commented on nsv13/code/modules/reagents/chemistry/recipes/drugs.dm
> +	required_reagents = list(/datum/reagent/medicine/liquid_solder = 1, /datum/reagent/medicine/system_cleaner = 1, /datum/reagent/medicine/radioactive_disinfectant = 1,/datum/reagent/uranium/radium = 1
```suggestion
	required_reagents = list(/datum/reagent/medicine/liquid_solder = 1, /datum/reagent/medicine/system_cleaner = 1, /datum/reagent/medicine/radioactive_disinfectant = 1, /datum/reagent/uranium/radium = 1)
```

2022-11-19 02:03 UTC, covertcorvid approved these changes

2022-11-25 23:32 UTC, covertcorvid approved these changes

2022-11-25 23:33 UTC, merged