[WIP] Ports Faxes from TG
BeeStation/NSV13 pull request #2131
Opened 2022-11-02 10:17 UTC by Bobbanz1

## About The Pull Request
This PR ports the fax machine, alongside the various PRs associated with it. 

Ports the following PRs:
[69083](https://github.com/tgstation/tgstation/pull/69083) 
[69397](https://github.com/tgstation/tgstation/pull/69397) 
[69554](https://github.com/tgstation/tgstation/pull/69554) 
[69651](https://github.com/tgstation/tgstation/pull/69651) 
[70072](https://github.com/tgstation/tgstation/pull/70072) 

## To-Do

- [ ] Write the changelog
- [ ] Add Fax machines to the current maps in Rotation
- - [ ] Tycoon
- - [ ] Aetherwhisp
- - [ ] Shrike?
- - [ ] Eclipse
- - [ ] Galactica
- - [ ] Atlas
- - [ ] Snake

## Why It's Good For The Game
Allows for closer IC interactions with Centcom/Admins through Faxes.

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

## Changelog
:cl:
add: Ported the Fax Machine
/:cl:

2022-11-02 20:30 UTC, Karmic-Skink requested changes
Update the CL to include the original PR author's handles.

2022-11-03 22:33 UTC, Bobbanz1 commented
> If you need any help, I can help you with implementation. But before you implement the port, I would advise you to look at the redesigned [TG paper](https://github.com/tgstation/tgstation/pull/68612), as well as the [Jolly fax variation](https://github.com/TaleStation/TaleStation).

I believe I was going to port the TG paper code system in this [PR](https://github.com/BeeStation/NSV13/pull/2023).

However I think the reason I ultimately choose not to do so was because of this, still open, [issue](https://github.com/tgstation/tgstation/issues/69261). The issue in question reported the experience of lag when writing on the paper.

2022-11-07 00:07 UTC, Karmic-Skink commented
Can this be integrated into requests consoles at all?

2022-11-07 07:15 UTC, Bobbanz1 commented
@Karmic-Skink Could you explain what the Request Console is?

2022-11-10 06:20 UTC, Bobbanz1 commented
@twilightwanderer 
Hey there, I'm currently having an issue with both the Fax Machine TGUI and the Fax Manager TGUI, the issue is two folded (think that's the correct word for it) 

The first part is that if someone were to deconstruct every fax machine except for one lone fax machine on the server, then the Fax Machine TGUI will bluescreen. 

The second part is that if someone were to deconstruct EVERY fax machine on the server, then the Fax Manager TGUI will bluescreen until a new fax machine is built or spawned in.

I don't actually know enough about TGUI code to implement some sort of fix for the problem and was hoping you might have an idea on how to fix these two issues?

2022-11-14 07:56 UTC, Bobbanz1 commented
> Update the CL to include the original PR author's handles.

This has been done

2022-11-16 20:25 UTC, Karmic-Skink commented
> @Karmic-Skink Could you explain what the Request Console is? Is it something that's related to Cargo or is it some sort of Admin panel thing?

![image](https://user-images.githubusercontent.com/45891563/202286665-d5747c09-4b9a-4c4d-be75-f944e577d490.png)

/obj/machinery/requests_console

2022-11-17 05:00 UTC, Bobbanz1 commented
> > @Karmic-Skink Could you explain what the Request Console is? Is it something that's related to Cargo or is it some sort of Admin panel thing?
> 
> ![image](https://user-images.githubusercontent.com/45891563/202286665-d5747c09-4b9a-4c4d-be75-f944e577d490.png)
> 
> /obj/machinery/requests_console

Ah that one....No I don't believe it could be integrated into that console.

2022-11-17 20:54 UTC, Karmic-Skink commented
> > > @Karmic-Skink Could you explain what the Request Console is? Is it something that's related to Cargo or is it some sort of Admin panel thing?
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/45891563/202286665-d5747c09-4b9a-4c4d-be75-f944e577d490.png)
> > /obj/machinery/requests_console
> 
> Ah that one. Short Answer: No I don't believe it could be integrated into that console.
> 
> Detailed explanation: It would require a full reworking of the Request Console UI, to the point where it would be so far out of the scope of what this PR is trying to do that it would be an entire separate PR that would also have to be ported to Bee.
> 
> Currently the Fax Machine runs on TGUI code, the request console runs using HTML code, in order to even try figuring out how such an integration would even theoretically be done, I'd have to upgrade the Request Console's UI to TGUI code, something I'm not that good at and porting some codebases request console where it has been upgraded would be an entirely separate PR worth of Content.

It makes far more sense to integrate the function of these devices rather than having additional machines in rooms that already contain machines designed to facilitate communications outside of direct radio comms.

2022-11-18 08:07 UTC, Bobbanz1 commented
> > > > @Karmic-Skink Could you explain what the Request Console is? Is it something that's related to Cargo or is it some sort of Admin panel thing?
> > > 
> > > 
> > > ![image](https://user-images.githubusercontent.com/45891563/202286665-d5747c09-4b9a-4c4d-be75-f944e577d490.png)
> > > /obj/machinery/requests_console
> > 
> > 
> > Ah that one. Short Answer: No I don't believe it could be integrated into that console.
> > Detailed explanation: It would require a full reworking of the Request Console UI, to the point where it would be so far out of the scope of what this PR is trying to do that it would be an entire separate PR that would also have to be ported to Bee.
> > Currently the Fax Machine runs on TGUI code, the request console runs using HTML code, in order to even try figuring out how such an integration would even theoretically be done, I'd have to upgrade the Request Console's UI to TGUI code, something I'm not that good at and porting some codebases request console where it has been upgraded would be an entirely separate PR worth of Content.
> 
> It makes far more sense to integrate the function of these devices rather than having additional machines in rooms that already contain machines designed to facilitate communications outside of direct radio comms.
> 
> So effectively a -1 from me, as it is just adding additional clutter to already complicated areas.

Could you clarify what areas are complicated?

2022-11-19 00:41 UTC, covertcorvid approved these changes

2022-11-19 04:01 UTC, Karmic-Skink requested changes
Several map design errors.

2022-11-19 04:06 UTC, covertcorvid requested changes
Apparently not being logged in breaks the fax manager

2022-11-19 06:21 UTC, Bobbanz1 commented on _maps/map_files/Shrike/Shrike1.dmm
> +/obj/machinery/fax{
I understand the issues but I really have to ask…How does a plant which isn’t even solid, restrict access around doors?

2022-11-19 08:01 UTC, Karmic-Skink commented on _maps/map_files/Shrike/Shrike1.dmm
> +/obj/machinery/fax{
Because you put a tripping hazard on the floor.

2022-11-19 21:29 UTC, Karmic-Skink commented
Could you please just revert all Shrike changes and I'll manually add them if this PR is merged. Thanks.

2022-11-20 19:50 UTC, Bobbanz1 commented
> Apparently not being logged in breaks the fax manager

Issue has potentially been solved as I haven’t received any more runtime errors from Dusklight, Altangy, Ta or any other admins since my last commit. 

However there are still issues with the PR that needs fixing and I’m positive that there’s probably going to be more runtime errors cropping up eventually, is there a tag that keeps this PR from being merged but still kept as Test Merged?

2022-12-02 06:45 UTC, Bobbanz1 commented
> This pull request has conflicts, please resolve those before we can evaluate the pull request.

DAMN IT NOT AGAIN

2022-12-03 18:36 UTC, covertcorvid approved these changes

2023-01-21 05:39 UTC, Bobbanz1 commented
It’s always the fucking hammerhead to have merge issues!

2023-03-14 06:34 UTC, covertcorvid commented
> > Apparently not being logged in breaks the fax manager
> 
> Issue has potentially been solved as I haven’t received any more runtime errors from Dusklight, Altangy, Ta or any other admins since my last commit.
> 
> However there are still issues with the PR that needs fixing and I’m positive that there’s probably going to be more runtime errors cropping up eventually, is there a tag that keeps this PR from being merged but still kept as Test Merged?

Are these issues fixed?

2023-03-14 07:14 UTC, Bobbanz1 commented
> > > Apparently not being logged in breaks the fax manager
> > 
> > 
> > Issue has potentially been solved as I haven’t received any more runtime errors from Dusklight, Altangy, Ta or any other admins since my last commit.
> > However there are still issues with the PR that needs fixing and I’m positive that there’s probably going to be more runtime errors cropping up eventually, is there a tag that keeps this PR from being merged but still kept as Test Merged?
> 
> Are these issues fixed?

I have not received any more issues from those admins howeverat the same time...this PR hasn't been test-merged in months and I'm still waiting on Beestation to get around to looking at the PR I made that updates the Papercode which would allow the admin interface to properly work.

2023-04-03 05:15 UTC, Bobbanz1 commented
After a few days of thought and a coin flip , I’ve come to a conclusion that I’ve reached the limit of what I can do for NSV, as such I’m going to slowly start pulling away from creating PRs and porting stuff for NSV13, as such I’m closing this PR.

2023-04-03 05:15 UTC, closed without merging

2023-04-03 05:34 UTC, covertcorvid commented
Sorry to hear that. I'd be willing to take this after re-verifying without having it ported to Bee if you were interested in that, but understandable if not.

2023-04-03 05:54 UTC, Bobbanz1 commented
> Sorry to hear that. I'd be willing to take this after re-verifying without having it ported to Bee if you were interested in that, but understandable if not.

I'll probably work on it again in the future once I've managed to regain some sort of future stability compared to the current crisis I'm facing, this PR is...well it works but it's also broken at the same time, it's missing specific PRs I was porting to Beestation to inevitably port downstream which would have made this PR work as it was supposed to work. 

Current issues are the following
* The formatting just does not work at all, you can't make fields nor do any of the formatting you can do on a regular piece of paper in-game.

2023-04-03 06:23 UTC, covertcorvid commented
Ah yeah, I remember that part not working. Best of luck with your situation.