fix chat badges for NSV ranks
BeeStation/NSV13 pull request #2139
Opened 2022-11-04 19:26 UTC by red031000

## About The Pull Request

fix badge

## Why It's Good For The Game

fix badge

## Changelog
:cl:
fix: fix badge
/:cl:

2022-11-06 21:24 UTC, Bokkiewokkie requested changes

2022-11-06 21:24 UTC, Bokkiewokkie commented on config/badges.json
> +    "Game Admin": "admin",
```suggestion
    "Admin": "admin",
    "Game Admin": "admin",
```
Keep the old ones as well

2022-11-06 21:24 UTC, Bokkiewokkie commented on config/badges.json
> +    "Head Admin": "headmin",
```suggestion
    "Headmin": "headmin",
    "Head Admin": "headmin",
```
Ditto

2022-11-08 23:55 UTC, covertcorvid approved these changes

2023-01-06 20:21 UTC, Bokkiewokkie approved these changes

2023-01-06 20:21 UTC, merged