Makes a Named Mulebot gain a new name!
BeeStation/NSV13 pull request #2192
Opened 2022-11-19 21:19 UTC by Bobbanz1

## About The Pull Request
Replaces a Mulebots name with a new Name!

## Why It's Good For The Game
Named Mulebots that are named after people are not good

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

## Changelog
:cl:
fix: Fixes a named Mulebot by giving it a new name!
/:cl:

2022-11-19 21:21 UTC, Bokkiewokkie submitted a review, later dismissed

2022-11-20 05:56 UTC, covertcorvid requested changes
If we're giving it a dog name can we either go with the traditional "Fluffy" or something else like, I dunno, Fido or Rover or Spot or whatever?
It's been pointed out that "fluffer" has a porn-related meaning

2022-11-20 14:23 UTC, Bobbanz1 commented
> If we're giving it a dog name can we either go with the traditional "Fluffy" or something else like, I dunno, Fido or Rover or Spot or whatever? It's been pointed out that "fluffer" has a porn-related meaning

Done, it's now a Metal Penguin called Mittens

2022-11-20 16:08 UTC, covertcorvid submitted a review, later dismissed

2022-11-25 23:45 UTC, covertcorvid commented on _maps/map_files/Tycoon/Tycoon2.dmm
> +	desc = "For some reason this strange looking metal penguin seems to have a sticker attached to it with the words Mittens written on it!"
```suggestion
	desc = "For some reason this strange looking metal penguin seems to have a sticker attached to it with the word Mittens written on it!"
```
One more nitpick - Mittens is one word

2022-11-26 12:03 UTC, Bobbanz1 commented on _maps/map_files/Tycoon/Tycoon2.dmm
> +	desc = "For some reason this strange looking metal penguin seems to have a sticker attached to it with the words Mittens written on it!"
🤏

2022-11-26 22:18 UTC, covertcorvid approved these changes

2022-11-26 22:52 UTC, merged