Nsv13 boarding changes
BeeStation/NSV13 pull request #2197
Opened 2022-11-21 20:59 UTC by DuskLight9978

## About The Pull Request
This PR makes changes to all syndicate boarding maps to make them more viable for ghost roles. Such as fighters for the Syndicate crew on the carrier, Medkits for the NT prisoner on the mako. Better turret placement. Reduced Health on the Barricade for the turret inside the Hellfire map. More maint spawns for loot. More syndicate docs for incentivizing boarding. Alongside many smaller changes.

## Why It's Good For The Game
Maintaining the boarding maps is good.

## Testing Photographs and Procedure
board_test used to load boarding maps and verify changes were consistent and not erroneous.
Bokkiewoki said not to add pictures, but to add pictures of spiderman so here you go.

<details>
<summary>Screenshots&Videos</summary>

![image](https://user-images.githubusercontent.com/55417034/203156370-8c6a7dff-b311-4e67-a944-6e7070aa7823.png)

</details>

## Changelog
:cl:
tweak: Tweaked the boarding maps.
fix: Added lights to Mako maps
/:cl:

2022-11-21 22:49 UTC, DuskLight9978 commented
Excellent, Green checks. Now for the taste test of quality.

2022-12-16 11:43 UTC, Bokkiewokkie requested changes

2022-12-16 11:43 UTC, Bokkiewokkie commented on _maps/templates/boarding/syndicate/mako_carrier.dmm
> +/obj/effect/spawner/lootdrop/ruinloot/medical,
```suggestion
/obj/effect/spawner/lootdrop/maintenance/six,
```
the medical lootdrop has some pretty gamer equipment, it's probably better to just use maintenance ones for these (and maybe add a single medical ruin loot spawner in the medbay?)
Images for reference:
![image](https://user-images.githubusercontent.com/43698041/208088447-a6c89e1d-8425-45bb-9526-d2d3a73a1622.png)
![image](https://user-images.githubusercontent.com/43698041/208088598-6cad6207-ce88-4cae-94db-07c867f07241.png)

2022-12-16 11:43 UTC, Bokkiewokkie commented on _maps/templates/boarding/syndicate/mako_carrier.dmm
> +/obj/effect/spawner/lootdrop/ruinloot/medical,
```suggestion
/obj/effect/spawner/lootdrop/maintenance/six,
```
Ditto regarding the ruin loot, you could have one or two in there but this is probably a bit much (seeing as it's also two crates)

2022-12-16 11:43 UTC, Bokkiewokkie commented on _maps/templates/boarding/syndicate/mako.dmm
> +/obj/effect/spawner/lootdrop/ruinloot/medical,
Same notes as with the mako carrier regarding these
```suggestion
/obj/effect/spawner/lootdrop/maintenance/six,
```

2022-12-16 11:43 UTC, Bokkiewokkie commented on _maps/templates/boarding/syndicate/mako.dmm
> +/obj/effect/spawner/lootdrop/ruinloot/medical,
```suggestion
/obj/effect/spawner/lootdrop/maintenance/six,
```
Ditto

2022-12-16 20:49 UTC, Bokkiewokkie approved these changes

2022-12-16 20:49 UTC, merged