makes all food forkable
BeeStation/NSV13 pull request #2210
Opened 2022-11-27 03:46 UTC by Pontenerd

## About The Pull Request

Lets you eat all food with forks (minus soups!)

## Why It's Good For The Game

Forks are good for eating

## Testing Photographs and Procedure
https://cdn.discordapp.com/attachments/602204705862582341/1044003786575855616/2022-11-20_21-37-43.mp4

## Changelog
:cl:
add: Added new things
add: Added more things
del: Removed old things
tweak: tweaked a few things
balance: rebalanced something
fix: fixed a few things
soundadd: added a new sound thingy
sounddel: removed an old sound thingy
imageadd: added some icons and images
imagedel: deleted some icons and images
spellcheck: fixed a few typos
code: changed some code
refactor: refactored some code
config: changed some config setting
admin: messed with admin stuff
server: something server ops should know
/:cl:

2022-11-28 12:44 UTC, Bokkiewokkie requested changes
Please port this to Beestation as well, or move the changes to the nsv13 subfolder if they do not want this change.

2022-12-18 23:34 UTC, Bokkiewokkie commented
Untestmerging as this is breaking other attackby() interactions with food!

2022-12-26 16:35 UTC, Bokkiewokkie requested changes

2022-12-26 16:35 UTC, Bokkiewokkie commented on _maps/map_files/Atlas/atlas2.dmm
> -	},
This is causing a conflict

2022-12-26 16:35 UTC, Bokkiewokkie commented on code/modules/food_and_drinks/food/snacks.dm
> +
```suggestion
			return
	..()
```
You should probably let every other thing go about the normal interaction :p

2022-12-26 16:35 UTC, Bokkiewokkie commented on code/modules/food_and_drinks/food/snacks.dm
> +			return ..()
```suggestion
			return
```

2022-12-26 16:35 UTC, Bokkiewokkie commented on code/modules/food_and_drinks/food/snacks.dm
> +		return ..()
```suggestion
/obj/item/kitchen/spoon/attack(mob/living/carbon/M, mob/living/carbon/user)
	. = ..()
	if(!istype(M))
		return
```

2022-12-26 16:35 UTC, Bokkiewokkie commented on code/modules/food_and_drinks/food/snacks.dm
> +		return ..()
```suggestion
		return
```

2022-12-26 16:35 UTC, Bokkiewokkie commented on code/modules/food_and_drinks/food/snacks.dm
> +		return ..()
```suggestion
/obj/item/kitchen/fork/attack(mob/living/carbon/M, mob/living/carbon/user)
	. = ..()
	if(!istype(M))
		return
```

2022-12-26 16:35 UTC, Bokkiewokkie commented on code/modules/food_and_drinks/food/snacks.dm
> +
```suggestion
		return
```

2022-12-26 16:40 UTC, Bokkiewokkie submitted a review, later dismissed

2023-01-02 17:43 UTC, covertcorvid submitted a review, later dismissed

2023-01-02 18:37 UTC, covertcorvid approved these changes

2023-01-06 19:39 UTC, Bokkiewokkie commented
Please update the [Beestation PR](https://github.com/BeeStation/BeeStation-Hornet/pull/8202) as wel.

2023-02-17 22:08 UTC, merged