NSV Simplemobs
BeeStation/NSV13 pull request #2251
Opened 2022-12-30 19:54 UTC by QAI-07

## About The Pull Request
Adds a selection of NSV Specific Simplemobs to the game!
They come with their own unique sprites, weapon types and other funky business.

So far it features:
Space and Normal syndicate mobs
Space Pirate mobs
Nanotrasen Mobs

## Why It's Good For The Game
Having mobs that don't fire lasers would be nice in the department of keeping things 'Lore Accurate'. They generally fit better with NSV as a whole aswell.

## Testing Photographs and Procedure
![simple_human](https://user-images.githubusercontent.com/64690217/210107291-00e7437d-a96e-4a4d-b044-827d00929e9f.png)
them

</details>

## Changelog
:cl:
add: Added a handful of new mobs to be used in events and mapping.
add: Added sprites for the aforementioned new mobs.
/:cl:

2022-12-30 21:32 UTC, Karmic-Skink reviewed
![image](https://user-images.githubusercontent.com/45891563/210113065-ac1eebe6-e0a9-4d89-aece-84f8b676c2bf.png)

2022-12-30 21:33 UTC, Karmic-Skink requested changes

2022-12-30 21:33 UTC, Karmic-Skink commented on nsv13/code/modules/mob/living/simple_animal/hostile/nsvsyndicate.dm
> +/*
This file is already under the nsv13 folder and thus doesn't need "nsv" in its title.

2022-12-31 19:35 UTC, QAI-07 commented
Due to multiple issues I have found whilst testing this, not to mention forgetting to actually finish the PR, I am closing this PR until it's actually done.

2022-12-31 19:35 UTC, closed without merging