Gives Winona much needed buffs
BeeStation/NSV13 pull request #2314
Opened 2023-02-09 12:19 UTC by someone543

## About The Pull Request
Buffs Winona by having burst fire like a standard MP glock, no decreased accuracy from one hand firing and full auto.

## Why It's Good For The Game
Winona is in desperate need of a upgrade, right now it is little more than a command glock with a fancy name and description, and to make it worse it doesn't even have burst fire like a standard MP glock. These changes seek to make Winona into something worth using. 

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

https://user-images.githubusercontent.com/95106800/217808489-b68218d0-b01c-4cc6-bae3-dfb9abc2e31b.mp4

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

## Changelog
:cl:
balance: Winona buffed. Burst fire, no one handed penalty, and full auto added
/:cl:

2023-02-09 12:33 UTC, TheScienceOfKSP commented
As a bonus, there's now a much bigger reason for her inclusion in Grand Theft objectives.

Also, much grander changes than i had dreamt off.

2023-02-10 09:19 UTC, Bokkiewokkie approved these changes

2023-02-10 21:31 UTC, covertcorvid requested changes

2023-02-10 21:31 UTC, covertcorvid commented on code/game/objects/structures/crates_lockers/closets/secure/security.dm
> +	new /obj/item/gun/ballistic/automatic/pistol/glock/security/hos(src)
Add NSV13 tags to core files pls

2023-02-10 21:46 UTC, someone543 commented on code/game/objects/structures/crates_lockers/closets/secure/security.dm
> +	new /obj/item/gun/ballistic/automatic/pistol/glock/security/hos(src)
Consider it done

2023-02-17 08:37 UTC, covertcorvid approved these changes

2023-02-21 05:37 UTC, merged