[PORT] The Hugbot
BeeStation/NSV13 pull request #2342
Opened 2023-03-09 17:48 UTC by Bobbanz1

## About The Pull Request
Completes one of the suggestions made on the forum: 
https://forums-nsv.beestation13.com/t/new-bots-title-needs-to-be-15-characters-soooooooo/183

This PR accomplishes that by porting the Hugbot from Skyrat13
In order to build a Hugbot you need 1 borg arm, attach it to a box of hugs(found in a hacked medical vending machine) and then add a proximity sensor to it. 

The Hugbot, as its name implies, goes about hugging crew members. It will however not hug crew members which have already got the hugged moodlet. 

The Hugbothas adjustable operating modes, allowing it to hug, pat and boop the snoot of the crew! ~~**HEADPATS FOR EVERYONE!!**~~

The Hugbot will provide helpful and friendly moral support to the crew by giving them friendly reminders that they are an important member of the crew, and that they are always loved.

If emagged, the Hugbot will hug a bit too hard, knock the crew down and replace it's friendly vocabulary with hostile statements.
## Ports From: Skyrat13
* https://github.com/Skyrat-SS13/Skyrat13/pull/3572

## Why It's Good For The Game
~~Furthers the Organic Replacement with Machines by replacing the Clown's job with a mindless Robot that hugs people~~
Adds a new Bot to the Game, one that can give you a peptalk and help keep the crews spirit up in the face of an all out space war

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

https://user-images.githubusercontent.com/59128051/224109895-c14524fa-c052-47f2-8dfc-3e1692fa9676.mp4

</details>

## Changelog
:cl:jbox144, Bobbanz1
add: Adds the hugbot
imageadd: Adds icons for the hugbot
imageadd: Adds the NSV13 file aibots.dmi
imagedel: Deleted the catmedbot.dmi file
code: Changed the icon path on the MediKitty to the newly created dmi file
/:cl:

2023-03-13 17:58 UTC, Kmc2000 commented on code/__DEFINES/robots.dm
> +#define HUG_BOT 			(1<<7)  //!  Hugbots //NSV13
I would suggest this goes in a modular file, if this is not possible I'm OK with taking this as is.

2023-03-21 04:14 UTC, covertcorvid requested changes

2023-03-21 04:14 UTC, covertcorvid commented on nsv13/code/modules/mob/living/simple_animal/bot/hugbot.dm
> +		path = get_path_to(src, get_turf(patient), /turf/proc/Distance_cardinal, 0, 30,id=access_card)
```suggestion
		path = get_path_to(src, patient, 30,id=access_card)
```
Our get_path_to doesn't need a proc definition and will do the get_turf itself

2023-03-21 04:14 UTC, covertcorvid commented on nsv13/code/modules/mob/living/simple_animal/bot/hugbot.dm
> +			path = get_path_to(src, get_turf(patient), /turf/proc/Distance_cardinal, 0, 30,1,id=access_card)
```suggestion
			path = get_path_to(src, patient, 30,1,id=access_card)
```

2023-03-21 04:14 UTC, covertcorvid commented on nsv13/code/modules/mob/living/simple_animal/bot/hugbot.dm
> +	// Hey, didyah know that you Han't hug people as non-carbon? Well you can't hug people as non-carbon. Hence this mess
fear

2023-03-21 04:14 UTC, covertcorvid commented on nsv13/code/modules/mob/living/simple_animal/bot/hugbot.dm
> +			if(S?.can_wag_tail(src) && !H.dna.species.is_wagging_tail())
```suggestion
			if(S?.can_wag_tail(src) && !(S?.is_wagging_tail()))
```

2023-03-21 04:14 UTC, covertcorvid commented on nsv13/code/modules/mob/living/simple_animal/bot/hugbot.dm
> +				var/static/list/many_tails = list("tail_human", "tail_lizard", "mam_tail")
```suggestion
				var/static/list/many_tails
				if(!many_tails)
					many_tails = list("tail_human", "tail_lizard", "mam_tail")
```

2023-03-21 06:56 UTC, Bobbanz1 commented on nsv13/code/modules/mob/living/simple_animal/bot/hugbot.dm
> +	var/tania_mode = 0 // When enabled, the hug bot will not change targets, and will hug regardless of mood
I have no idea really, could try hunting down the original PR creator but I haven't got the faintest idea where I'd even start.

Could probably be a reference to something but a quick google search reveals nothing.

2023-03-21 17:41 UTC, covertcorvid commented on nsv13/code/modules/mob/living/simple_animal/bot/hugbot.dm
> +	var/tania_mode = 0 // When enabled, the hug bot will not change targets, and will hug regardless of mood
You can leave it, I was just curious. Not curious enough for you to go to the effort of hunting someone down

2023-03-21 17:42 UTC, covertcorvid approved these changes
o7

2023-04-03 05:36 UTC, merged