Fixes missing variables in sabre FTL component
BeeStation/NSV13 pull request #2360
Opened 2023-03-25 00:07 UTC by covertcorvid

## About The Pull Request
Fixes a reported issue with sabre FTL, pylons not actually drawing power, and swarmer-proofs some stuff

## Why It's Good For The Game
Missing variables make things not work.
Things that use power as a mechanic should use power.
Irreplaceable equipment shouldn't get eaten by swarmers. 

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

## Changelog
:cl:
fix: Fixed sabre FTL missing a variable
fix: FTL pylons will now add load to the power grid
balance: FTL machines can no longer be eaten by swarmers
/:cl:

2023-03-25 00:15 UTC, Bokkiewokkie approved these changes
Can't believe I missed these when fixing the other missing variable

2023-03-25 00:20 UTC, covertcorvid commented
> Can't believe I missed these when fixing the other missing variable

Not actually sure req_charge is needed, I was just checking every reference to ftl_drive that I could see

2023-03-25 06:57 UTC, Karmic-Skink requested changes

2023-03-25 06:57 UTC, Karmic-Skink commented on nsv13/code/modules/overmap/FTL/components/drive.dm
> +	return FALSE
Can we please print an IC message here as to why.
Just copy paste from the other system critical devices.

2023-03-25 06:57 UTC, Karmic-Skink commented on nsv13/code/modules/overmap/FTL/components/drive_pylon.dm
> +	return FALSE
Ditto.

2023-03-25 06:57 UTC, Karmic-Skink commented on nsv13/code/modules/overmap/FTL/ftl_legacy.dm
> +/obj/machinery/computer/ship/ftl_computer/swarmer_act(mob/living/simple_animal/hostile/swarmer/S)
Dritto.

2023-03-26 21:50 UTC, Karmic-Skink approved these changes

2023-04-09 01:38 UTC, merged