Allows one late join cyborg
BeeStation/NSV13 pull request #2391
Opened 2023-04-11 12:17 UTC by someone543

## About The Pull Request
Increases total position for the cyborg job to 1, meaning that if nobody took the round start cyborg slot, a player can late join as a cyborg.

## Why It's Good For The Game
If nobody joined as a round start cyborg, we should be able to late join the empty slot

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

## Changelog
:cl:
tweak: Cyborg total positions set to 1
/:cl:

2023-04-11 13:07 UTC, someone543 commented
Also made the PR on beestation https://github.com/BeeStation/BeeStation-Hornet/pull/8853. If it doesn't get merged there, I'll add the //NSV13 comment

2023-04-11 22:10 UTC, Karmic-Skink requested changes
As this is a core file, it requires an //NSV13 tag

2023-06-09 18:15 UTC, Bokkiewokkie approved these changes

2023-06-16 17:12 UTC, Bokkiewokkie approved these changes

2023-06-21 02:42 UTC, merged