Enables Byond 515
BeeStation/NSV13 pull request #2400
Opened 2023-04-19 23:30 UTC by covertcorvid

## About The Pull Request
Enables serverside and clientside 515 support.

## Why It's Good For The Game
Performance

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

## Changelog
:cl:
server: Upped the compiler version and max client version to 515.1604
/:cl:

2023-04-20 10:33 UTC, Bokkiewokkie approved these changes
Hm yes higher numbers

2023-04-20 11:56 UTC, Karmic-Skink commented on dependencies.sh
> +export BYOND_MINOR=1604
Time traveller.

2023-04-20 11:57 UTC, Bokkiewokkie requested changes

2023-04-20 11:57 UTC, Bokkiewokkie commented on dependencies.sh
> +export BYOND_MINOR=1604
```suggestion
export BYOND_MINOR=1603
```
Byond 1604 hasn't released yet so that's probably not gonna do much

2023-04-20 11:57 UTC, Bokkiewokkie commented on code/_compile_options.dm
> +#warn WARNING: Your BYOND version is over the recommended version (515.1604)! Stability is not guaranteed.
```suggestion
#warn WARNING: Your BYOND version is over the recommended version (515.1603)! Stability is not guaranteed.
```

2023-04-20 11:57 UTC, Bokkiewokkie commented on code/_compile_options.dm
> +#define MAX_COMPILER_BUILD 1604
```suggestion
#define MAX_COMPILER_BUILD 1603
```

2023-04-20 17:09 UTC, covertcorvid commented
This is the version BeeStation is also using for the beta
https://github.com/BeeStation/BeeStation-Hornet/pull/8784

2023-04-20 17:10 UTC, Bokkiewokkie approved these changes

2023-04-26 19:30 UTC, Crossedfall reviewed
The sendmaps beta has been moved into 515.1605

2023-04-26 19:30 UTC, Crossedfall commented on dependencies.sh
> +export BYOND_MINOR=1604
```suggestion
export BYOND_MINOR=1605
```

2023-04-26 19:30 UTC, Crossedfall commented on code/_compile_options.dm
> +#define MAX_COMPILER_BUILD 1604
```suggestion
#define MAX_COMPILER_BUILD 1605
```

2023-04-26 19:30 UTC, Crossedfall commented on code/_compile_options.dm
> +#warn WARNING: Your BYOND version is over the recommended version (515.1604)! Stability is not guaranteed.
```suggestion
#warn WARNING: Your BYOND version is over the recommended version (515.1605)! Stability is not guaranteed.
```

2023-04-30 16:05 UTC, Crossedfall reviewed
bump bump bump

2023-04-30 16:05 UTC, Crossedfall commented on code/_compile_options.dm
> +#define MAX_COMPILER_BUILD 1606
```suggestion
#define MAX_COMPILER_BUILD 1607
```

2023-04-30 16:05 UTC, Crossedfall commented on code/_compile_options.dm
> +#warn WARNING: Your BYOND version is over the recommended version (515.1606)! Stability is not guaranteed.
```suggestion
#warn WARNING: Your BYOND version is over the recommended version (515.1607)! Stability is not guaranteed.
```

2023-05-04 22:03 UTC, Bokkiewokkie submitted a review, later dismissed
We just gonna keep jumping up 📈

2023-08-12 08:01 UTC, Kenionatus commented
Last active: 2 months ago
Label: Active test merge
Me: 🤔

2024-06-09 01:40 UTC, covertcorvid commented
@Bokkiewokkie I'm tried of waiting for Bee to merge theirs, should we pull the trigger?

2024-06-12 10:28 UTC, Bokkiewokkie commented
> @Bokkiewokkie I'm tried of waiting for Bee to merge theirs, should we pull the trigger?

Sure, we can just make a new PR if something new is actually done for it

2024-06-12 10:29 UTC, Bokkiewokkie approved these changes

2024-06-14 14:04 UTC, merged