[Upstream] HoP Expansion Pack - Papers Please Edition
BeeStation/NSV13 pull request #2434
Opened 2023-05-29 07:15 UTC by Bobbanz1

## About The Pull Request
Pulls from Upstream the Gigantic Paperwork Rework
* https://github.com/BeeStation/BeeStation-Hornet/pull/8821

This PR also merges the fax machines added to most of our maps from:
* https://github.com/BeeStation/NSV13/pull/2131 

Alongside merging the changes made in this PR to the photocopier and integrating the altered code with the Beestation photocopier machine: 
* https://github.com/BeeStation/NSV13/pull/2023

IT also ports from TG-Station the fix that makes the forms created from the photocopiers actually work.
* https://github.com/tgstation/tgstation/pull/73633

(To whoever decides to go through and review all this stuff, **_I'm sorry_**)

## Why It's Good For The Game
A more up to date version of the Paperwork Module, allows people to see the result of what they're entering on a paper, fax machines to annoy admins with and other fun stuff!

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

![204471147-20920092-bdf3-403e-8f5d-b2f684be6f25](https://github.com/BeeStation/NSV13/assets/59128051/90658e13-cc93-48c6-b679-396b987d405a)

</details>

## Changelog
:cl:Bobbanz1, Timberpoes, SteelSlayer, twilightwanderer, ShizCalev, timothymtorres, Imaginos16, dragomagol, Jacquerel, Mothblocks, ThePotato97, LemonInTheDark
del: Removed the ability to scan paper directly into the modular computer notes app as part of paper code rewrite.
qol: AIs now see the full paper interface when players show them papers through the camera, exactly what's written on the paper, fully rendered.
refactor: Paper code has been completely refactored.
fix: Fixes signatures not working at all. Signatures now only work when %s or %sign is put into an [___] input field.
fix: Input fields are now fixed and also work again.
fix: Fixes broken command report formatting for station goals.
fix: Fixes markdown paragraphing not working in paper code.
refactor: Photocopiers now use TGUI
tweak: You can insert any type of toner cartridge into photocopiers, and regardless of the currently inserted toner's charge level.
tweak: Toner cartridges can be ejected from photocopiers at any time
add: Added a system of forms and the ability to print them
fix: Hints in bureaucracy forms
add: Added new VOID stamp
fix: Photocopier paperforms
add: Fax Machine
fix: Fixes faxes playing the "fax_contain" animation and makes it actually use the "fax_receive" animation when receiving.
imageadd: Resprites fax machines!
admin: fax messages and book printings are now logged in paper.log
admin: renaming fax machines is logged in game log
add: You can now send photos or trading cards through the fax machine.
add: You can now hack the wires of a fax machine to have it throw items harder or accept additional flat input items such as material sheets, ID cards, and pizza slices.
add: Ability to send and receive administrator fax messages.
admin: Panel for easy viewing and sending messages to faxes.
fix: Fixes a crash of TGUI fax panel when there is no fax in the network
fix: Fixes a crash of the Fax Manager panel when there is no fax machines in the network.
refactor: Rotating stamps on paper by holding shift and moving your mouse.
fix: You can no longer remove the toner cartridge from a printer while it's busy printing.
fix: Fixes broken input fields on photocopied paper.
/:cl:

2023-06-02 11:26 UTC, Bokkiewokkie requested changes
Mapping review:
You should swap the tables in Tycoon engineering there, they can't actually reach the fax machine in that corner.
Also, please give the Atlas bridge a pen for that paper bin and a command folder on a table somewhere to sort their documents 🙏

2023-06-02 12:44 UTC, Bobbanz1 commented
> Mapping review:
> You should swap the tables in Tycoon engineering there, they can't actually reach the fax machine in that corner.

That’s there by tradition but I’ll make it happen.

> Also, please give the Atlas bridge a pen for that paper bin and a command folder on a table somewhere to sort their documents 🙏

I’ll make it happen later today.

2023-06-09 18:19 UTC, Bokkiewokkie submitted a review, later dismissed
Mapping approved

2023-06-29 05:47 UTC, covertcorvid approved these changes
LGTM

2023-07-07 20:51 UTC, merged