Makes latejoins wake up from cryostasis instead of arriving on a shuttle
BeeStation/NSV13 pull request #2466
Opened 2023-07-01 16:20 UTC by covertcorvid

## About The Pull Request
It makes latejoins wake up from cryostasis instead of arriving on a shuttle

## Why It's Good For The Game
Thematic

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

![cryo](https://github.com/BeeStation/NSV13/assets/17987483/0606fdef-0f32-46c0-8ede-da698f468b77)

</details>

## Changelog
:cl:
del: Removed arrivals shuttles
tweak: Late joiners will now spawn near the cryostasis pods
/:cl:

2023-07-01 22:15 UTC, SerynEngi commented
Might I ask that you not change the Galactica, Hammerhead, and Aetherwhisp and have me make those changes instead on those maps to avoid mapping conflicts with already open PRs? Particularly as the Galactica and Aetherwhisp fixes in particular fix critical flaws in the maps.

2023-07-01 22:32 UTC, covertcorvid commented
Don't even know if we want this, but even if we do it's low priority and your PRs should be done first

2023-07-04 14:38 UTC, Bokkiewokkie requested changes
This should also update the automated announcement system message to state someone has awoken from cryostasis

2023-07-13 08:57 UTC, Kmc2000 approved these changes
Love this.

2023-07-28 16:09 UTC, Bokkiewokkie approved these changes

2023-07-28 16:09 UTC, merged