Overmap Ship normal damage type immunity
BeeStation/NSV13 pull request #2493
Opened 2023-07-29 04:33 UTC by SerynEngi

## About The Pull Request

This PR adds armor to overmap ships of all types for all non-shipboard overmap armor types.

## Why It's Good For The Game

Reduces/prevents the rare overmap bug exploitation from killing ships.

## Changelog
:cl:
fix: Added normal armor to all overmap ships.
/:cl:

2023-07-31 15:03 UTC, Bokkiewokkie requested changes
They shouldn't have 100 bomb protection because explosions on the overmap are funny (they can still have a lot, however).
Fire damage is also applied by incendiary weapons and shouldn't have any.

2023-08-04 11:53 UTC, DeltaFire15 requested changes
This is so much copypasta, maybe make a OVERMAP_BASE_RESISTANCES define and put the copypasted part of the armor list in there? Since defines are replaced at compile time it should be fine to use in that list.

2023-08-04 15:29 UTC, Bokkiewokkie commented
> This is so much copypasta, maybe make a OVERMAP_BASE_ARMOR_VALUES define and put the copypasted part of the armor list in there? Since defines are replaced at compile time it should be fine to use in that list.

Agree with this, it also makes it easier to adjust globally (since I see you still missed a couple of fire armour values)

2023-08-05 00:26 UTC, Karmic-Skink commented
There is a proc to add armour values that be added to late initialize etc

2023-08-11 16:53 UTC, Bokkiewokkie commented
> There is a proc to add armour values that be added to late initialize etc

@SerynEngi can you actually do this instead, you only have to add it to the /obj/structure/overmap type once

2023-08-11 16:55 UTC, Bokkiewokkie requested changes
see comment above

2023-08-17 12:17 UTC, Bokkiewokkie approved these changes
Yes excellent commit :+1:

2023-08-25 16:51 UTC, merged