Atlas Atmospherics Rebuild
BeeStation/NSV13 pull request #2498
Opened 2023-07-30 22:19 UTC by SerynEngi

## About The Pull Request

This PR rebuilds Atlas's atmospherics to comply with the standard reactor mixer piping layout and simplifies the layout for understanding.

## Why It's Good For The Game

The rebuilt atmos complies with the standard O2/N2/CO2/N20/Constricted Plasma layout present on other ships, and greatly simplifies the piping in atmospherics on the atlas, allowing for greater adaptation and usage of the space.

## Testing Photographs and Procedure

![AtlasAtmosBeforeAfter](https://github.com/BeeStation/NSV13/assets/75588150/7567d444-1fd0-4c37-9919-f5ed979fdcce)

## Changelog
:cl:
tweak: Rebuild Atlas atmospherics for ease of use.
/:cl:

2023-08-02 07:38 UTC, Brillcrafter commented
Oh god, this means that I will have to update the wiki page if this is permanently merged. Fun

2023-08-04 12:33 UTC, BlueHNT commented
> Oh god, this means that I will have to update the wiki page if this is permanently merged. Fun

The setup is mostly the same so I don't think you will have to. As the only changes are spaghetti clearing.

2023-08-04 12:57 UTC, SerynEngi commented
> > Oh god, this means that I will have to update the wiki page if this is permanently merged. Fun
> 
> The setup is mostly the same so I don't think you will have to. As the only changes are spaghetti clearing.

They will have to, somewhat. The ship now complies with the standard O2/N2/CO2/N20/Constricted plasma setup that every other ship runs. It did not do so previously, as the ship (prior to this PR) runs it in the following order: CP/N2/Plasma/N20/CO2/O2.

I've wanted to do this for some time, but other people were modifying the map, and other things took priority.

2023-08-04 15:31 UTC, Bokkiewokkie requested changes

2023-08-04 18:19 UTC, Bokkiewokkie approved these changes
Love these last two commits they're the best!

2023-08-18 11:40 UTC, merged