Allows cyborgs to pilot transport small craft
BeeStation/NSV13 pull request #2504
Opened 2023-08-04 15:04 UTC by someone543

## About The Pull Request
Allows cyborgs to use the flight console on transport small craft such as Sabres and the dropship. 

## Why It's Good For The Game
Cyborgs could already use the helm console on the Rocinante to mine on their own, so they should be able to use Sabres on their own as well. 

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

TBA

</details>

## Changelog
:cl:
tweak: Cyborgs can now fly transport small craft
/:cl:

2023-08-04 16:16 UTC, Bokkiewokkie submitted a review, later dismissed

2023-08-05 00:19 UTC, Karmic-Skink requested changes
Smol craft are intentionally not pilotable by cyborgs as design decision.

2023-08-05 00:32 UTC, Karmic-Skink commented
By nature silicons are very powerful and can do a lot of things that carbons cannot.
In balance, this requires silicons to be unable to perform a number of actions, as they are not supposed to be able to be a one player show.

Piloting smol ships falls into this as it:
- Prevents low/no risk fighter gameplay
- Prevents low/no risk boarding action

2023-08-18 11:09 UTC, someone543 commented
> By nature silicons are very powerful and can do a lot of things that carbons cannot. In balance, this requires silicons to be unable to perform a number of actions, as they are not supposed to be able to be a one player show.

While I agree with borgs not being a one player show, there are still several things that borgs can't do that carbons can.
Cyborgs are still, without the help of a carbon, unable to do the following:
- Refuel small craft with a fuel pump
- Repair and reinstall armor plates or a canopy
- Fix and reinstall a flooded engine
- Exchange fighter parts with better parts

This means, if a mining borg wants to fly alone to mine they still can, just with a couple more risks. As mentioned above, a mining borg can already use the Rocinante to mine by themselves, why shouldn't they be able to use Sabres to do the same?

> 
> Piloting smol ships falls into this as it:
> 
>     * Prevents low/no risk fighter gameplay
Completely understandable. This PR limits borgs to only transport craft after all
>     * Prevents low/no risk boarding action
A little bit confused about this, so I'll assume you mean a boarding party comprised of mostly/all cyborgs? 
Because if so, then this would already be possible. Just have one carbon with a bunch of reboot boards fly the dropship for them.

2023-08-18 11:26 UTC, Bokkiewokkie commented
Closing this because it conflicts with future development and I agree it'd be better not to have it right now because removing it again after that would just be lame.

2023-08-18 11:26 UTC, closed without merging