Galactica Xenobio Fixes
BeeStation/NSV13 pull request #2507
Opened 2023-08-05 18:09 UTC by SerynEngi

## About The Pull Request

Fixes https://github.com/BeeStation/NSV13/issues/2506 and adds a tank dispenser to atmos.

## Why It's Good For The Game

Fix Man Good

## Changelog
:cl:
add: Added an breathing air tank dispenser to atmos storage on the Galactica
fix: Fixed a couple mapping issues with the Galactica Xenobio
/:cl:

2023-08-11 16:44 UTC, Bokkiewokkie commented
![image](https://github.com/BeeStation/NSV13/assets/43698041/cbd74dd5-c320-44d6-a505-959115181e2b)
There's supposed to be like, openspace here, so people can actually walk up/down the stairs

2023-08-11 18:37 UTC, SerynEngi commented
> ![image](https://user-images.githubusercontent.com/43698041/260070150-cbd74dd5-c320-44d6-a505-959115181e2b.png) There's supposed to be like, openspace here, so people can actually walk up/down the stairs

I haven't noted the stairs not functioning as intended there, but you're right, it may help people to notice that there are stairs there.

2023-08-12 19:21 UTC, Bokkiewokkie requested changes
Don't put electric grilles like that delivery one on a mail pipe like that. If security leaves a convict in a room with the shutter open that's on them. Prisoners can still get gulag points from torp building without it being opened.
You've also left a lone window and disposal pipe in the hallway outside munitions.

2023-08-12 22:02 UTC, SerynEngi commented
> Don't put electric grilles like that delivery one on a mail pipe like that. If security leaves a convict in a room with the shutter open that's on them. Prisoners can still get gulag points from torp building without it being opened. You've also left a lone window and disposal pipe in the hallway outside munitions.

![muni output updated](https://github.com/BeeStation/NSV13/assets/75588150/35d9f597-9c21-4102-a04e-9cd212e6f626)

2023-08-13 18:50 UTC, Bokkiewokkie approved these changes

2023-09-01 17:07 UTC, merged