attempts a fix to the overlapping borg crew manifest hud
BeeStation/NSV13 pull request #2510
Opened 2023-08-10 01:36 UTC by bruhlookatthisdood

## About The Pull Request

~~I was going to move it above radio, but I really didn't want to block off more screen with hud, so I decided to make a small button for it, next to the language button.~~
i am moving it to the cyborg computer
fixes #2273 

## Why It's Good For The Game

buttons not overlapping each other is good 👍 

## Testing Photographs and Procedure

before
![image](https://github.com/BeeStation/NSV13/assets/89947174/fd53948e-aab6-4021-98f9-8a9e108a29cb)
after
![image](https://github.com/BeeStation/NSV13/assets/89947174/083df3eb-bcdb-4007-b1e8-249ea4f7d9b4)

## Changelog
:cl:
fix: fixed borg crew manifest button overlapping
/:cl:

2023-08-10 18:48 UTC, Bokkiewokkie requested changes
Either also PR this change to beestation or add //nsv13 tags mentioning the removed stuff.
(Since it's a bug fix I highly recommend the former). You also don't need to remove the icon if you opt to choose the latter.

2023-08-10 18:50 UTC, bruhlookatthisdood commented
> Either also PR this change to beestation or add //nsv13 tags mentioning the removed stuff. (Since it's a bug fix I highly recommend the former). You also don't need to remove the icon if you opt to choose the latter.

Apperantly not an issue on beestation, i'll double check though.

2023-08-11 16:35 UTC, Bokkiewokkie commented on nsv13/code/modules/overmap/armour/nano_well.dm
> +	if(!(in_range(src, usr) || IsAdminGhost(usr))) //nsv changed | to ||
```suggestion
	if(!(in_range(src, usr) || IsAdminGhost(usr)))
```
Don't need to add a comment to our own code

2023-08-11 18:34 UTC, Bokkiewokkie approved these changes

2023-08-25 16:53 UTC, merged