Hardtacks, for pirates, sea-farers and landlubbers alike.
BeeStation/NSV13 pull request #2539
Opened 2023-09-09 22:04 UTC by SharkeeByond

## About The Pull Request

Ahoy! This PR adds a small fluff item, hardtacks.

## Why It's Good For The Game

This PR adds another NSV-specific item, ment for the pirates. You can also use it to beat people to death!

## Testing Photographs and Procedure

Ensure you have 2 containers with atleast 10 units of flour and water nearby, Do NOT mix them, this will create flour instead!
Open the crafting table and go to "Breads", on the bottom of the list will be "Hardtack"
Craft, it should appear below your character.

<details>
<summary>Screenshots&Videos</summary>

![image](https://github.com/BeeStation/NSV13/assets/74540553/04ace3af-555b-43ff-a776-4d65713b2897)
![image](https://github.com/BeeStation/NSV13/assets/74540553/26f1fd82-2454-475d-8054-f3ce6ac426c9)

</details>

## Changelog
:cl:
add: Added hardtacks!
imageadd: Hardtack sprite
code: Hardtack code and recipe
/:cl:

2023-09-10 05:06 UTC, Karmic-Skink requested changes
Please move these all to the custom files in the NSV13 folder.

2023-09-10 08:24 UTC, SharkeeByond commented
> Please move these all to the custom files in the NSV13 folder.

Should be done now

2023-09-15 17:30 UTC, Bokkiewokkie requested changes

2023-09-15 17:30 UTC, Bokkiewokkie commented on nsv13/code/modules/food_and_drinks/food/custom_food.dm
> +/obj/item/reagent_containers/food/snacks/hardtack //NSV13
You don't need to keep the NSV tags when it's already in a custom file, and you need to include these files in the nsv13.dme file as well ("ticking" it in dream maker or VSC)

2023-09-15 17:30 UTC, Bokkiewokkie commented on nsv13/code/modules/food_and_drinks/food/custom_food.dm
> +	force = 9
I suspect you wanted to use `throwforce` for this, or possibly just also add it.

2023-09-15 17:30 UTC, Bokkiewokkie commented on nsv13/code/modules/food_and_drinks/food/custom_food.dm
> +	icon_state = "hardtack"
```suggestion
	desc = "Traditional pirate snack. Legally considered a dangerous weapon."
	icon = 'nsv13/icons/obj/food.dmi'
	icon_state = "hardtack"
```
Need the custom icon *file* referenced here as well

2023-09-15 17:30 UTC, Bokkiewokkie commented on nsv13/code/modules/food_and_drinks/recipes/tablecraft/recipes_custom
> +	subcategory = CAT_BREAD
This file has no extension, and ditto on the commenting and including in .dme

2023-09-19 22:06 UTC, SharkeeByond commented
Closing this PR for now, too busy with irl stuff to continue. Those who are willing to start this PR again by themselves may use the sprites provided.

2023-09-19 22:06 UTC, closed without merging