Roundstart Nucleum
BeeStation/NSV13 pull request #2542
Opened 2023-09-21 22:41 UTC by SerynEngi

## About The Pull Request

This PR creates an engineering turf for nucleum and adds that turf to the maps with the Thirring FTL Drive.

## Why It's Good For The Game

Crewmen can now start moving larger ships before the 10 minute mark. Mappers no longer have to tweak a variable.

## Changelog
:cl:
add: Added new nucleum preset engineering tile
tweak: Added nucleum gas to the nucleum tanks on the Galactica, Tycoon and Aetherwhisp
/:cl:

2023-09-22 18:57 UTC, Bokkiewokkie approved these changes
We'll change the numbers based on the test merge if it turns out to be too much/little roundstart gas

2023-09-29 21:30 UTC, Bokkiewokkie requested changes
While you're changing the gladius room, could you add a fire alarm, extinguisher, and intercom to it?

2023-10-03 05:43 UTC, SerynEngi commented
> While you're changing the gladius room, could you add a fire alarm, extinguisher, and intercom to it?

Added. Intercom already existed in the little status corner for both engineering and common channels.

2023-10-06 20:02 UTC, Bokkiewokkie approved these changes

2023-10-06 20:03 UTC, merged