NSV Materials Fix
BeeStation/NSV13 pull request #2558
Opened 2023-10-03 02:40 UTC by Ikalpo

## About The Pull Request

makes the NSV material amounts look nicer in code
fixes the durasteel sheet material amount (it was missing a bit of titanium)
fixes the amount NSV materials cost in ORMs and lathes
adds material amounts to `tile/carpet/ship` (they are made of durasteel)

## Why It's Good For The Game

![fix man good](https://user-images.githubusercontent.com/23534908/222276620-9eb46bcf-ea6b-418c-beb1-4ba7c82a5f8d.gif)
and also I want to be able to recycle those floor tiles when I accidently make them

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

![image](https://github.com/BeeStation/NSV13/assets/23534908/b7d94485-c4f4-4b72-88a8-9eb6425c5215)

</details>

## Changelog
:cl:
fix: You can now recycle nanoweave carpet tiles
fix: Fixed the amount that NSV materials cost in ORMs and lathes
/:cl:

2023-10-03 07:04 UTC, Karmic-Skink commented
![image](https://github.com/BeeStation/NSV13/assets/45891563/050e149f-dceb-4cdf-911c-f751429d6b8c)

The implication that the green there looks nicer in code is 100% subjective and also 1000% the wrong choice.

2023-10-06 19:59 UTC, Bokkiewokkie commented
> ![image](https://user-images.githubusercontent.com/45891563/272173168-050e149f-dceb-4cdf-911c-f751429d6b8c.png)
> 
> The implication that the green there looks nicer in code is 100% subjective and also 1000% the wrong choice.

Yeah @Ikalpo you should just make it one decimal or fraction

2023-10-06 21:46 UTC, Ikalpo commented
> > ![image](https://user-images.githubusercontent.com/45891563/272173168-050e149f-dceb-4cdf-911c-f751429d6b8c.png)
> > The implication that the green there looks nicer in code is 100% subjective and also 1000% the wrong choice.
> 
> Yeah @Ikalpo you should just make it one decimal or fraction

is `list(/datum/material/iron = MINERAL_MATERIAL_AMOUNT*0.2/4, /datum/material/silver = MINERAL_MATERIAL_AMOUNT*0.15/4, /datum/material/titanium = MINERAL_MATERIAL_AMOUNT*0.65/4)` better?

2023-10-06 23:58 UTC, Karmic-Skink commented
> > > ![image](https://user-images.githubusercontent.com/45891563/272173168-050e149f-dceb-4cdf-911c-f751429d6b8c.png)
> > > The implication that the green there looks nicer in code is 100% subjective and also 1000% the wrong choice.
> > 
> > 
> > Yeah @Ikalpo you should just make it one decimal or fraction
> 
> is `list(/datum/material/iron = MINERAL_MATERIAL_AMOUNT*0.2/4, /datum/material/silver = MINERAL_MATERIAL_AMOUNT*0.15/4, /datum/material/titanium = MINERAL_MATERIAL_AMOUNT*0.65/4)` better?

No

2023-10-07 09:32 UTC, Karmic-Skink commented
Okay so firstly, you are making this far more complicated than it needs to be. It really does not need to contain any operations to determine what the exact number needs to be and just makes it harder to read.

![image](https://github.com/BeeStation/NSV13/assets/45891563/94c1ca7c-06db-4562-9cc3-d764a4266165)
Consider this image.
When we are taught mathematics at school, we are first taught fractions as these are the easiest numbers for our human brains to make sense of.
As we progress, we move forward into decimals and scientific nomenclature.
Which most adults have somewhat an understanding of.

By adding basically a horrible inverse of a fraction using decimals and including operators, you are effectively making it extremely hard to read for no real reason.

tl;dr there is absolutely nothing wrong with using fractions or straight decimals, please stop trying to reinvent the wheel.

2023-11-03 16:57 UTC, Bokkiewokkie requested changes
Agree with Karmic on the readability of multiplications here (btw karmic just request changes for it next time)

2023-11-10 19:15 UTC, Bokkiewokkie approved these changes

2023-11-10 19:41 UTC, merged