[BUGFIX] FTL Navigation Console is no longer able to be used everywhere
BeeStation/NSV13 pull request #2643
Opened 2024-05-11 16:44 UTC by tontyGH

## About The Pull Request

fixes #2045
removes the always_state override from the FTL console and adds a missing parent check to ui_act()

## Why It's Good For The Game

![930fa64abea7372f70f8ee7453da222d](https://github.com/BeeStation/NSV13/assets/39193182/91a93522-aca9-4a0d-8bbc-fead14af41d1)

## Testing Photographs and Procedure
<details>
<summary>Screenshots&Videos</summary>

https://github.com/BeeStation/NSV13/assets/39193182/78d80695-6e2b-427c-85c3-28daa4f45baf
##
Admin ghost interaction

https://github.com/BeeStation/NSV13/assets/39193182/1fff175a-434c-4462-9627-91d7b2a35f1c

</details>

## Changelog
:cl: tonty
fix: the FTL navigation console no longer grants hyperspecific telekinesis to people who use it
/:cl:

2024-05-11 17:00 UTC, DeltaFire15 requested changes

2024-05-11 17:00 UTC, DeltaFire15 commented on nsv13/code/modules/overmap/starmap.dm
> +	if(..() && !IsAdminGhost(usr))
preserve parent return value.
. = ..()
if(. && [...]

2024-05-11 18:19 UTC, DeltaFire15 approved these changes

2024-05-14 03:20 UTC, covertcorvid approved these changes

2024-05-14 05:34 UTC, merged