[Port] Hardsuit Tails
BeeStation/NSV13 pull request #2715
Opened 2024-10-16 16:16 UTC by DeltaFire15

## About The Pull Request
Some talk on NSV led me to remember I saw armored tails on hardsuits somewhere somewhen. In turn, I did manage to remember where I remembered that from, tracked down where they ported it from, and, in turn, ported that here.

This essentially ports https://github.com/Skyrat-SS13/Skyrat-tg/pull/2183, albeit without Vulpine sprites (We don't have Foxes. Except Renault.), aswell as doing some mildly "funky" implementation stuff because our mutant bodypart overlay proc (and especially accessory backend) vary, even relative to the point of time this is from.

For now has the same color setups as the base PR (luckily, as opposed to bee, most of our hardsuits still have "old" sprites).
However, that also means that some NSV-unique suits do currently lack this, like Pilot Hardsuits.
I've spent enough of today's brain power on this for now though, so we'll see at some point.

See screenshots section for included suits.

The Felinid tails are also kind of, big, compared to how they look without a suit, eh better than them being like three pixels wide (maybe the suit is just thick!). Do tell if you prefer them this way or crammed into the suit, no big feelings in either direction (except it not being very comfy to have a tail in there aswell as the rest of you).

## Why It's Good For The Game
Bluespace Tail Storage is expensive.

Having your tail just vanish when you put on a hardsuit has been a minor recurring annoyance across servers for me. Now they do not, and you have some more distinction even in hardsuits.

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

Base suits (minus RD and HOS because I oopsied):
![tailsuits_standard_ANN](https://github.com/user-attachments/assets/5c7b2d9c-0b59-4fe5-825b-7799d8ddfd2e)

RD & HOS suit (because I oopsied):
![OOPS_ANN](https://github.com/user-attachments/assets/d7659b44-1301-4aac-8174-7db93e8008c9)

Special suits:
![tailsuits_special_ANN](https://github.com/user-attachments/assets/02745e49-0ce4-4ae0-a44b-0f80a3046992)

</details>

## Changelog
:cl: NotRanged, Azarak, DeltaFire15
add: Tails should now be visible in hardsuits that support them.
imageadd: Tails in hardsuits.
/:cl:

2024-10-16 17:08 UTC, Bokkiewokkie requested changes
Since this is NSV13, can we also add tail color combinations for our own suits? They should all be in nsv13/icons/mob/suit.dmi, if you need a color reference. I feel like the skinsuit, radsuit, and regular EVA suit (and pirate eva suit) would all also make sense (even more so than the actual hardsuits) to give tails.
On top of this, the current "colored" part of the ERT suit tails seems a bit oversaturated, maybe you can just pick a color from the actual suit for those (I assume the colors are different because Skyrat has some more vibrant suits)

The rest looks fine, originally I was surprised to see code instead of sprites, but it's executed quite nicely here.

2024-10-16 18:16 UTC, DeltaFire15 commented
> Since this is NSV13, can we also add tail color combinations for our own suits? 

That is the intent, I just spent hours thinking about how to translate that implementation from their more bespoke overlay 
handling here and have zero energy left to see about cooking overlay values.

>I feel like the skinsuit, radsuit, and regular EVA suit (and pirate eva suit) would all also make sense

Note to self.

>On top of this, the current "colored" part of the ERT suit tails seems a bit oversaturated, maybe you can just pick a color from the actual suit for those (I assume the colors are different because Skyrat has some more vibrant suits).

We can certainly adjust values if needed since the handling was made for that.

> The rest looks fine, originally I was surprised to see code instead of sprites, but it's executed quite nicely here.

It certainly is a useful implementation since it makes it easy for compat for new suits, albeit at some slightly lower variance, but it suffices unless someone decides to sprite tails for days.

2024-12-08 17:27 UTC, DeltaFire15 commented
Current Flightsuit take (kinda dark? Unfortunately staring at 32x32 sprite colors for too long makes my head hurt but feel free to try your own palettes)
![image](https://github.com/user-attachments/assets/ea88f0b6-48c7-4cc9-bd51-bd6ea6bb11f5)

(The rogue pixel on the cat is NOT me, that is a Flightsuit sprite issue that also occurs on master)

2025-01-10 18:22 UTC, Bokkiewokkie commented
Merging this, we can add other color variations in a new PR

2025-01-10 18:23 UTC, merged