Tycoon Medical Dept. Update and Tycoon/Atlas Damage Control Central
BeeStation/NSV13 pull request #2728
Opened 2024-12-14 01:47 UTC by SerynEngi

## About The Pull Request

This PR updates Tycoon Medical to the current mapping standards, as well as adds Damage Control storerooms for storage of damage control supplies in central locations and Damage Control Central which is a central location for engineers to help monitor damage status. Also deletes virology from Tycoon.

## Why It's Good For The Game

Tycoon medical department has been brought up to current standards and organization. Virology is being phased out due to it not suiting NSV gameplay. 

Damage Control Central gives engineers a method of helping and interacting with the crew for damage control without them _only_ being maintenance tunnel gremlins. The damage control storerooms, when opened by an engineer, provide the crew with actual spacesuits and the means to fight their local casualties.

As part of the damage control section of this PR, I borrowed the areas.dm and areas.dmi from my Gungnir branch to create the associated area and to reduce future conflicts.

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

![TycoonMedicalBeforeAfter](https://github.com/user-attachments/assets/05e1f58b-0891-46c2-a19c-3799adea8eff)

![Atlas Changes](https://github.com/user-attachments/assets/c6e91054-0643-4451-b0bd-d799d31ebf29)

![Tycoon Changes](https://github.com/user-attachments/assets/96e44d51-2720-481c-b63b-4c9b9d8c2b6c)
</details>

## Changelog
:cl:
add: Added Damage Control Central to Atlas and Tycoon
add: Added Damage Control Lockers (Storerooms) to Atlas and Tycoon
tweak: Redesigned Tycoon medical department
tweak: Updated areas.dm and areas.dmi for new engineering areas
del: Removed virology division and job from Tycoon
/:cl:

2024-12-14 12:35 UTC, DeltaFire15 commented
Removal of virology (the physical department section) seems very rash. Virology tasks still appear in bounties, and virological threats still occur with variable frequency. 
While removal of the job is fairly reasonable (overlaps with other med jobs while itself running out of tasks fast), I do not agree with the removal of the map aspect.

2024-12-14 19:13 UTC, SerynEngi commented
> Removal of virology (the physical department section) seems very rash. Virology tasks still appear in bounties, and virological threats still occur with variable frequency. While removal of the job is fairly reasonable (overlaps with other med jobs while itself running out of tasks fast), I do not agree with the removal of the map aspect.

Virology functionality is still possible, The pandemic machine and virus food are presently located within chemistry, and the sole virus extrapolator is has been relocated to the CMO locker. You just can't do the job without the CMO's permission unless you print an extrapolator and you cant screw off to Narnia for a whole round from the start.

Its probably a fair guess that the virologist job is entirely too embedded in the code to fully get rid of without a lot of work, and honestly, thats not the goal. The goal is to remove incentives for people to ignore the ship for the whole round. Atlas suffers not at all from having it gone and I see that as just as likely here.

2024-12-15 09:49 UTC, someone543 commented
A condiments box is missing next to the new coffee machine in medical (thank you for adding that by the way). Please add one.

2024-12-16 21:26 UTC, SerynEngi commented
Re-added virology area as ablative armor and antag space. Be warned- extremely easy to depressurize. Air alarms, door and APC in that area are all access. Map-lore switched to "collision with a hammerhead class destroyer after refit completed".

![Virology Ablative Armor](https://github.com/user-attachments/assets/685b8e4c-05ea-4d16-a3ba-31994705f9ae)

2024-12-28 09:11 UTC, SerynEngi commented
Added a quick and dirty fix to this disposal pipe routing. I'll do a better fix when I rework the department in a different PR.

![Tycoon Delivery quick Fix](https://github.com/user-attachments/assets/ca6f15d5-918a-4de5-a43f-880272eca8e8)

2024-12-29 03:32 UTC, SerynEngi commented
Added Borg chargers to the following locations: Medical Equipment room, near the primary stairs to upper deck (near CIC), munitions missile factory, the cafeteria, departures, x2 near the cryo-tubes (for entering and leaving the round) and the hallway near botany.

2025-01-30 12:49 UTC, Bokkiewokkie requested changes
Here are the things I noticed after a first pass over the Tycoon.

There are some wallmounts covering the escape pod in the engineering hangar + some exposed pipes in the office there and a random water tank. If you want pipes to be visible, just use the ones that go over floors.
The damcon office also does not feature a fire extinguisher or fire alarm.
Remember to put firedoors under airlocks, the dcc office also does not have those.
There is an air alarm in front of a wall in medical maintenance.
Genetics has a bunch of wall mounts on a window.
The disposal bin in the middle of chemistry seems a bit in the way, to me, maybe replace one of the tables or just move it up a space at least?
Since there is space for two janitors, maybe add a second cleaning cart? The custodial closet still has some space in front of that APC if you need to move things around.
The KNPC nodes are missing the "tycoon deck 2 ladder" node, which used to resort in the tool storage and point to "tycoon deck 1 ladder" please replace this or the KNPC pathing chain will remain broken.
The new storage rooms do not contain fire or air alarms. a fire extinguisher cabinet may also be helpful.
Please do not use an unmarked passive vent in space for waste pipes, just a named injector is fine (and of course make sure it's in a powered area).

2025-01-30 18:06 UTC, BetaCentari commented
Took a look over medical, first it looks incredible. It's shored up very nicely, things are moved around very well and a lot more efficiently than they were before and make a lot more sense. 

Just a few things: 
1. There's no patient/quarantine rooms, I understand viro is on it's way out but it's something the tycoon had before. You could replace some of the old viro with some patient rooms or dig into the north west maint. Having a place for longer term patients to recover or infected patients to wait for a cure is a nice thing to have and there's plenty of room to spare. 

2. I could've easily missed it, but I'd like there to be a straight jacket, it was in the room above oxygen distro previously and you could move it to med storage along with the syringe gun. 

3. I think the techfab could do better in med storage. Could move the defibs or remove them since all med lockers come with a defib by default or place defibs in place of the techfab. I think it just makes more sense to have deeper into medical and near all the other equipment and items. 

4. I'd like a white linens locker put in the northwest corner of the trauma center with the cryo tubes like how it used to

Again, really really happy with the redux, everything's put in a much better place or given room where it was very much needed and the symmetry looks really nice. That's all I have for the time being.

2025-02-09 02:12 UTC, Bokkiewokkie commented
Other details I've seen so far:
Some of the cyborg chargers are in awkward spots, like right next to the kitchen counter, or in front of a chair in munitions. Maybe move those to a less jarring spot (like the little theatre lounge area and the munitions hallway?) The charger at the central staircase is also layered above the railing, which should be easy to fix.
The hallway outside of munitions is dark, so is the old virology crossing area (which has two lamps next to eachother in maint to the right).
It could be fun to add some more things to the end of that munitions hallway, even if it is just a table and a vending machine.
You may also want to move the door of the engineering hangar up one tile, for aesthetics, and put a lamp on the corner of the wall next to it for more illumination.
Surgery can be accessed from maintenance, the command meeting room can be accessed from the formerly public EVA hallway crossing. (note that the area being public is fine, just not that you can walk into the head meeting room from it w/o access).
The sofa in the theatre is rotated wrong.
Finally, a suggestion.
Since you have now removed tool storage in favour of a damage control locker, you may want to refurbish the top deck former damage control/squad area into a new public tool storage, or otherwise do something else more interesting with it.
I'll leave that up to you, though.

2025-02-15 04:44 UTC, SerynEngi commented
> Finally, a suggestion. Since you have now removed tool storage in favour of a damage control locker, you may want to refurbish the top deck former damage control/squad area into a new public tool storage, or otherwise do something else more interesting with it. I'll leave that up to you, though.

This will be handled in the service/cargo rework in a subsequent PR to avoid increasing scope even further than it already is. Intentions are to rework the public tool storage into the mostly-unused area near the hallway to engineering.

2025-02-15 11:46 UTC, Bokkiewokkie approved these changes

2025-02-15 11:47 UTC, merged