Allows midshipmen that are not assigned to important departments to be in squads.
BeeStation/NSV13 pull request #2732
Opened 2024-12-18 12:35 UTC by someone543

## About The Pull Request
If a midshipmen is not assigned to a department, or assigned to a department that is not essential to the ship (cargo and science) they will be assigned to a squad instead.

## Why It's Good For The Game
Midshipmen that are assigned to medical, engineering and munitions should be expected to help their respective departments, but if they're not assigned to any department, or assigned to a department that already allows squads, then they should be in a squad.

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

![itworks](https://github.com/user-attachments/assets/6accb098-429a-4859-8bf3-ba3dbe9fa060)

</details>

## Changelog
:cl:
tweak: Midshipmen that are not assigned to important departments get put in squads
/:cl:

2024-12-18 13:48 UTC, Bokkiewokkie submitted a review, later dismissed
Nice

2024-12-18 18:25 UTC, DeltaFire15 requested changes
`/datum/job` datums are uniques, meaning a single instanced object (per job) is used for all players. Using a variable on the job datum will cause issues as each player modifies the same variable of the same object.

2024-12-22 00:45 UTC, someone543 commented
Changed to check for id access instead of using a variable.

2024-12-22 17:18 UTC, Bokkiewokkie approved these changes

2024-12-22 19:52 UTC, DeltaFire15 submitted a review, later dismissed
Evil variable names but should work.

2024-12-27 19:25 UTC, DeltaFire15 approved these changes

2025-01-03 16:24 UTC, merged