groundwork: repair procs
BeeStation/NSV13 pull request #887
Opened 2020-09-13 09:40 UTC by Karmic-Skink

## About The Pull Request
Contains procs for repairing the ship overmap status

## Why It's Good For The Game
Precursor for [REDACTED]
Also for admin busing I guess

## Changelog
:cl:
add: Added some groundwork procs for later features
admin: easier overmap ship repairs
/:cl:

2020-09-13 09:48 UTC, Kmc2000 requested changes

2020-09-13 09:48 UTC, Kmc2000 commented on nsv13/code/modules/overmap/armour/armour_quadrant.dm
> +/obj/structure/overmap/proc/full_repair_instant() //Admin Override
```suggestion
/obj/structure/overmap/proc/repair_full() //Admin Override
```

2020-09-13 09:48 UTC, Kmc2000 commented on nsv13/code/modules/overmap/armour/armour_quadrant.dm
> +/obj/structure/overmap/proc/modular_structure_repair(var/input, var/failure = 0) //Input is the amount you want repaired per call of this proc, failure is the chance the repair will go wrong
```suggestion
/obj/structure/overmap/proc/repair_structure(var/input, var/failure = 0) //Input is the amount you want repaired per call of this proc, failure is the chance the repair will go wrong
```

2020-09-13 09:48 UTC, Kmc2000 commented on nsv13/code/modules/overmap/armour/armour_quadrant.dm
> +/obj/structure/overmap/proc/modular_armour_repair_quadrant(var/input, var/failure = 0, var/bias = 50, var/quadrant) //Input is the amount you want repaired per call of this proc, failure is the chanc
```suggestion
/obj/structure/overmap/proc/repair_quadrant(var/input, var/failure = 0, var/bias = 50, var/quadrant) //Input is the amount you want repaired per call of this proc, failure is the chance the repair will go wrong, bias is the favour for structure damage vs armour damage
```

2020-09-13 09:48 UTC, Kmc2000 commented on nsv13/code/modules/overmap/armour/armour_quadrant.dm
> +/obj/structure/overmap/proc/modular_armour_repair_all(var/input, var/failure = 0, var/bias = 50) //Input is the amount you want repaired per call of this proc, failure is the chance the repair will g
```suggestion
/obj/structure/overmap/proc/repair_all_quadrants(var/input, var/failure = 0, var/bias = 50) //Input is the amount you want repaired per call of this proc, failure is the chance the repair will go wrong, bias is the favour for structure damage vs armour damage
```

2020-09-13 14:18 UTC, francinum commented
Could the last two procs not be combined, and the all behavior be triggered by `quadrant = null`?

2020-09-18 05:32 UTC, francinum commented on nsv13/code/modules/overmap/armour/armour_quadrant.dm
> +/obj/structure/overmap/proc/full_repair() //Admin Override
Could you add these as VV dropdown entries?

2020-09-24 01:15 UTC, francinum commented on nsv13/code/modules/overmap/armour/armour_quadrant.dm
> +		if(!check_rights(NONE)) //Hmm?
```suggestion
		if(!check_rights(R_DEBUG)) //Hmm?
```

2020-09-26 10:14 UTC, Kmc2000 approved these changes

2020-09-26 10:14 UTC, merged