More Aetherwhisp fixes
BeeStation/NSV13 pull request #894
Opened 2020-09-17 03:37 UTC by IndusRobot

## About The Pull Request

This is a list that has accumulated over about 3 weeks 

Change sec techfab to sec protolathe, with console
Change medical techfab to medical protolathe, with console 
Rename area HOP to XO office
Add like 5 or 6 more sinks in security. Particularly around the detention cells For no particular reason
Move stormdrive fuel mix pipes from N2O to N2
Change purple fuel mix pipes to orange
Move reactors down 1, to allow space for gas pumps
Nuclear reactor implementation 
Need flex seal 
Tear up connectors, lay down 1 reactor 
Atmospherics external airlock not configured correctly 
Need uranium fuel rods 
Replace plating with all reinforced plating, keep pool
Connect nuclear reactor SMES to department distribution, yellow
Update atmospherics for RBMK fuel line
Add vacant commissary to empty compartment next to cryo bay 
Add second empty munitions for expansion, link it to first munitions with a disposal transit pipe
Add more pepperspray dispensers to brig, and make sure there's at least one in each department office
Move botany disk drive to the right 1 tile, so both table tiles are accessible
Turn on and maximize atmos-to-toxins multiz pipe 
Add one plasma and three oxygen canister to toxins
Bridge maintenance, bridge external airlock and captains office area shenanigans
Update SM setup to condense some stuff and some stuff to save time building burn chamber
Move 2 atmospheric lockers to engineering storage, as people typically check there for those and they're walking right past the current ones
Check to make sure science servers are cool enough for operation at round start
Replace distro gas pumps at top left with digital valves
Check for double APC in munitions
Discuss with staff, removing sniper rifle and energy weapons from armory 
Check again for doublepipe, particularly near stormdrive. There was a report of at least 1
Door to server room extension is just called engine room wing 
Added ribbon to CE office, as they get no medal box
Virology space injector and disposal needs medmaint area
Fixed a few duplicate APCs, missing APCs airalarms and cameras
Replace 2 plasma canisters with 2 carbon dioxide canisters
Move supermatter hot and cold loops connector ports so they take up less space, use layers 1 and 3
Add heat exchange to SM green cold loop and hotloop filters
Move supermatter firealarms away from windows
Move engineering hallway firealarm near storage away from singulo containment
Move engineering storage firealarm away from singulo containment
Stormdrive fuel chamber window is consistently being broken when stormdrive is low on fuel. Added shutters
Swap supermatter monitoring and department monitoring, relabel department monitoring to supermatter monitoring
Security and Medical department SMES output must be upgraded to 50 kw roundstart, department demand is too high right now
Change atmospherics solid to glass type variant
Sabre fighters are wrong prebuilt variant, need to select a prebuilt type
Add pool floaties
Ship still has a bad reputation for OOMing. Check for double pipes again
Add two fire axes
Missing air alarm in xenobio 
Missing request console in telecomms
Unable to access Command Server and Engineering Server, room must be expanded 
No double nuclear_waste_spawner effects found
Remove botany floor lights
Added a couple more blast doors to brig cells
Moved lawyer laptop down 1
Remove almost* all hull repair juice, noob trap
Remove armor plating 
check kitchen cold room to make sure isn't cooling stuff anymore 
Add airlock-ish to xenobio coldroom
Remove cable bridge between stormdrive to SMES and stormdrive to shields, in SMES room
Replace munitions puce locker with normal munitions locker, as it detracts from the value of the random puce event
Replace 6 stasis units and 6 sleepers with 3 stasis units and 3 sleepers, distributed in 6 patient rooms

## Why It's Good For The Game

2020-09-17 04:09 UTC, Vasily2013 requested changes
- [x] Medbay has a protolathe and a techfab. You forgot to yeet one.
- [x] Medbay doesn't have an R&D console
- [x] I think Whisp atmos may require a root canal. Not saying it's bad, but it is quite confusing in terms of layout.
This is a lot of changes, and I'll get them all reviewed in time. I think the fastest method may be to do an experimental test.

2020-10-03 12:28 UTC, Kmc2000 approved these changes

2020-10-03 12:28 UTC, Kmc2000 commented
> * [ ]  Medbay has a protolathe and a techfab. You forgot to yeet one.
> * [ ]  Medbay doesn't have an R&D console
> * [ ]  I think Whisp atmos may require a root canal. Not saying it's bad, but it is quite confusing in terms of layout.
>   This is a lot of changes, and I'll get them all reviewed in time. I think the fastest method may be to do an experimental test.

@IndusRobot

2020-10-08 23:52 UTC, Vasily2013 approved these changes
Yay, fixes!

2020-10-08 23:52 UTC, merged