Stormdrive Phase 4
BeeStation/NSV13 pull request #908
Opened 2020-09-28 08:25 UTC by Karmic-Skink

## About The Pull Request
Reworks Stormdrive Meltdown to be:

- Less Ship-wide Deadly
- More Locally Deadly
- Recoverable From

NOTE: CONTAINS TEMPORARY SPRITES AS I'M NOT A SPRITER

NOTE: #907 and #906 need to be resolved in conjunction with this

## Why It's Good For The Game
You can rebuild the stormdrive after meltdown
Meltdown more interesting

## Changelog
:cl:
add: Added the ability to rebuild the stormdrive following meltdown
add: Added a purchasable stormdrive core from cargo
refactor: Reworked the stormdrive meltdown
/:cl:

2020-09-28 10:58 UTC, Kmc2000 requested changes

2020-09-28 10:58 UTC, Kmc2000 commented on nsv13/code/modules/power/stormdrive.dm
> +/obj/machinery/atmospherics/components/binary/stormdrive_reactor/proc/storm_zap(atom/source, zap_range = 3, power, tesla_flags = TESLA_DEFAULT_FLAGS, list/shocked_targets) //This is so EHHHHHH but CB
This looks heavily copypasted from tesla.dm, you should refactor this into a component.

2020-09-28 10:58 UTC, Kmc2000 commented on nsv13/code/modules/power/stormdrive.dm
> +	var/static/blacklisted_tesla_types = typecacheof(list(/obj/machinery/atmospherics,
Why are you making things static in a proc? Static is for global member access by subclasses and is unnecessary as you're just redefining the static list over and over again with each usage of this proc

2020-09-28 10:58 UTC, Kmc2000 commented on nsv13/code/modules/power/stormdrive.dm
> +	var/static/blacklisted_tesla_types = typecacheof(list(/obj/machinery/atmospherics,
(And again, put this as a field on a tesla_zap component so it can be modified meaningfully)

2020-09-28 10:58 UTC, Kmc2000 commented on nsv13/code/modules/power/stormdrive.dm
> +		canshock = 0 //Just so you don't instakill yourself if you slam into the anomaly five times in a second.
```suggestion
		canshock = FALSE //Just so you don't instakill yourself if you slam into the anomaly five times in a second.
```

2020-09-28 10:58 UTC, Kmc2000 commented on nsv13/code/modules/power/stormdrive.dm
> +	desc = "This crate contains a live reactor core for a class iv nuclear storm drive."
```suggestion
	desc = "This crate contains a live reactor core for a class IV nuclear storm drive."
```

2020-09-28 10:58 UTC, Kmc2000 commented on nsv13/code/modules/power/stormdrive.dm
> +			to_chat(user, "<span class='notice'>Yhe reactor shielding has been reinforced.</span>")
```suggestion
			to_chat(user, "<span class='notice'>The reactor shielding has been reinforced.</span>")
```

2020-09-28 16:28 UTC, Vasily2013 commented
you can also use the "closes" preceding the issue number iirc, and that will link the issues.

2020-09-28 22:05 UTC, Karmic-Skink commented
> you can also use the "closes" preceding the issue number iirc, and that will link the issues.
> 
> Edit: Additional note: Please reference issues #906 and #907 with regards to the nuclear waste spawners.

These won't close these issues and aren't supposed to close them.

2020-10-03 12:31 UTC, Kmc2000 approved these changes

2020-10-03 12:31 UTC, merged