Munitions - MAA Consoles Update
BeeStation/NSV13 pull request #919
Opened 2020-10-04 10:40 UTC by Karmic-Skink

## About The Pull Request
This PR includes a console for the MAA's office that displays the current load of all the ship to ship weapons.

## Why It's Good For The Game
Allow MAA to easily check if weapons are loaded.
Fix a few bugs.

## Changelog
:cl:
add: Added ORD console for MAA office
add: Added ORD console board
fix: Fixed Tac Console datums incorrectly being linked to Ship Weapons datums
fix: Fixed Fighter Control Console techweb node getting deleted
/:cl:

2020-10-04 12:00 UTC, Kmc2000 requested changes

2020-10-04 12:00 UTC, Kmc2000 commented on nsv13/code/modules/overmap/components.dm
> +/obj/machinery/computer/ship/ordnance/ui_act(action, params)
Unecessary

2020-10-05 02:54 UTC, Karmic-Skink commented on nsv13/code/modules/overmap/components.dm
> +/obj/machinery/computer/ship/ordnance/attack_hand(mob/user)
Ehhhhh parent has stuff about positions and piloting, while it shouldn't actually proc. I though it would be cleaner to not include it.

2020-10-05 03:11 UTC, Karmic-Skink commented on nsv13/code/modules/overmap/components.dm
> +/obj/machinery/computer/ship/ordnance/attack_hand(mob/user)
Yes this is required to avoid the early return.

2020-10-09 11:22 UTC, Kmc2000 approved these changes

2020-10-09 11:23 UTC, merged