The Rook, A mining ship for the SGV Atherwhisp
BeeStation/NSV13 pull request #999
Opened 2020-10-27 06:03 UTC by theboy6545

## About The Pull Request

Adds a new mining ship, the SGV Rook, exclusive to the Atherwhisp,and changes the JSON to allow it.

## Why It's Good For The Game

Going from a solgov vessel to an NT one felt weird, and new stuff is always liked, right?
## Changelog
:cl:
add: Added a new ship, the SGV Rook.

/:cl:

2020-10-27 18:23 UTC, DrSirKnight commented
I'm just a player so my opinion doesn't matter, but the bottom area looks a bit stale.

2020-10-28 05:46 UTC, theboy6545 commented
> I'm just a player so my opinion doesn't matter, but the bottom area looks a bit stale.

Yeah, i couldn't really think of anything to put in there, plus it feels weird mapping over atmos pipes

2020-11-12 00:00 UTC, Vasily2013 commented
I think this looks ready for a test merge.

2020-11-20 11:34 UTC, Karmic-Skink commented on .gitignore
> +nsv13.dme
You what?

2020-11-21 02:32 UTC, Vasily2013 requested changes
remove the change to the gitignore and this'll get speedmerged as soon as I figure out why local testing no worie.

2020-11-23 14:46 UTC, Vasily2013 requested changes
This air alarm is too deep inside the wall, I'd suggest using the preset version that will put it closer to the south corner of the sprite. This appears to be an issue with all air alarms.
![image](https://user-images.githubusercontent.com/43328793/99974372-d3eb5580-2d6e-11eb-9e52-a631479fde35.png)

There are no air alarms in the washroom, bedroom, or the PACMAN generator room.

Additionally there is an air alarm in the bridge that is placed under a solgov logo, this should be altered. Otherwise from a bare bones functionality standpoint it looks good.

2020-11-26 17:56 UTC, theboy6545 commented
Alright, made all the requested changes.

2020-11-29 22:34 UTC, Vasily2013 commented
![image](https://user-images.githubusercontent.com/43328793/100555383-1af2b280-3269-11eb-8c86-95d635022403.png)
round-start active turfs. You want to use airless tiles here.

2020-11-30 11:01 UTC, theboy6545 commented
RIP travis, and the changes are done.

2020-12-03 18:13 UTC, Vasily2013 approved these changes
YEET

2020-12-03 18:13 UTC, merged